### ISSUE TITLE
[Feature] Consider extracting inline aleo programs out to separate files

### ISSUE THREAD

**Issue by facundoolano** [AleoHQ/snarkVM#1058]
For readability and browsability of the project, it would be good to extract the "built-in" programs in SnarkVM, such as the [credits program](https://github.com/AleoHQ/snarkVM/blob/e2ed1c8cb9d3f4692be4dd1f7b5bbb8f4c41ccfa/vm/compiler/src/program/mod.rs#L105), out to separate files, and include them in rust with [include_str](https://doc.rust-lang.org/std/macro.include_str.html).

**Comment by howardwu** [comment]
Agreed, assigning @raychu86 for adding a test harness for these tests.
