### ISSUE TITLE
[Proposal] Consider using squash merges for pull-requests

### ISSUE THREAD

**Issue by facundoolano** [AleoHQ/snarkVM#1066]
## 💥 Proposal
Current merges bring each individual commit on a PR, usually including WIP and intermediate broken commits into the history and mixing commits from different PRs. Squash merges would help to keep a cleaner git history of the project and understanding what gets merged when.

**Comment by howardwu** [comment]
I recommend we make this switch post-mainnet. Anecdotally, when multiple contributors were working on the library with squashes in the past, there were corner cases when merge conflicts became unresolvable from squashed commits.
