### ISSUE TITLE
[Proposal] Consider removing pass-through methods

### ISSUE THREAD

**Issue by facundoolano** [AleoHQ/snarkVM#1082]
## 💥 Proposal

A pass-through method is one that does nothing except pass its arguments to another method, usually with the same API as the pass-through method. This increases the interface complexity of a module, without increasing the total functionality of the system.

There are some instances of this in the codebase, for example the ledger [contains](https://github.com/AleoHQ/snarkVM/blob/44b1802589b3cdcd84acc0752210b212f203dfc3/vm/compiler/src/ledger/contains.rs)  and [iterators](https://github.com/AleoHQ/snarkVM/blob/44b1802589b3cdcd84acc0752210b212f203dfc3/vm/compiler/src/ledger/iterators.rs) modules. Those modules, in addition to defining methods [separated from their struct](https://github.com/AleoHQ/snarkVM/issues/1064), just define pass-through methods to access the same method in some of the ledger fields. As far as I can tell those methods even though public aren't being accessed outside the ledger impl; as an example, favoring `self.program_ids()` not only requires augmenting the interface complexity and the total amount of code, but actually provides less information than when calling its implementation directly: `self.transactions.program_ids()`

**Comment by howardwu** [comment]
Closing as the issue has been resolved in snarkVM
