### ISSUE TITLE
[Proposal] Verify required imports are deployed prior to deploying a new program

### ISSUE THREAD

**Issue by ncontinanza** [AleoHQ/snarkVM#1089]
## 💥 Proposal

Currently we are able to deploy a program that imports other aleo programs without previously deploying them, and we shouldn't be able to. 
In the following PR there's a possible implementation to solve this: https://github.com/AleoHQ/snarkVM/pull/1052/files

**Comment by howardwu** [comment]
Closing as this issue was fixed.
