### ISSUE TITLE
Use a checked power of two method for added safety

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkVM#1103]
We have many instances of `.next_power_of_two()` which should be switched to the checked variant as per this PR.

_Originally posted by @howardwu in https://github.com/AleoHQ/snarkVM/issues/1091#issuecomment-1256969379_

**Comment by ljedrz** [comment]
Happy to take this one; I checked the applicable source and it seems that there should be no noticeable performance penalty, so this can be applied liberally.
