### ISSUE TITLE
[Bug] Record serialization is not compatible with JSON

### ISSUE THREAD

**Issue by ilitteri** [AleoHQ/snarkVM#1114]
## 🐛 Bug Report

Client applications need to be able to consume the records as JSON, for example, applications using the wasm module, and currently, the values are returned in this pretty printed format upon serialization as follows:
```json
"{\n  owner: aleo1snwe5h89dv6hv2q2pl3v8l9cweeuwrgejmlnwza6ndacygznlu9sjt8pgv.private,\n  gates: 1u64.private,\n  _nonce: 4447510634654730534613001085815220248957154008834207042015711498717088580021group.public\n}"
```

### Trigger the bug using `to_string()`

Testing program:
```rust
use snarkvm::prelude::{Testnet3, Ciphertext, Record, ViewKey};

use std::str::FromStr;

fn main() {
    let view_key = ViewKey::from_str("AViewKey1dcqVNvMqYGoVtaQJW1YnmH23XABeeQTq9d6XmYUmo7CW").unwrap();
    let record_ciphertext = Record::<Testnet3, Ciphertext<Testnet3>>::from_str("record1qyqspplg2ud9gguy8ud9wjmee3cf2vztxcjxe2ernf8m7ru5wvsqkdqxqyqsq7y540qmemqx3675pufewwmywsudzrpstjx3fd38c6d8uz4r4mgpqqqt2q2jjczxp2y6986zdqz3mr5jmhggmge3exc72vgw2kgr4gea2zgzhrz8q").unwrap();
    let record = record_ciphertext.decrypt(&view_key).unwrap();

    println!("{:?}", record.to_string());
}

```
Build and run:
```shell
"{\n  owner: aleo1snwe5h89dv6hv2q2pl3v8l9cweeuwrgejmlnwza6ndacygznlu9sjt8pgv.private,\n  gates: 1u64.private,\n  _nonce: 4447510634654730534613001085815220248957154008834207042015711498717088580021group.public\n}"
```

### Trigger the bug from serialization
```rust
use snarkvm::prelude::{Testnet3, Ciphertext, Record, ViewKey};

use std::str::FromStr;

fn main() {
    let view_key = ViewKey::from_str("AViewKey1dcqVNvMqYGoVtaQJW1YnmH23XABeeQTq9d6XmYUmo7CW").unwrap();
    let record_ciphertext = Record::<Testnet3, Ciphertext<Testnet3>>::from_str("record1qyqspplg2ud9gguy8ud9wjmee3cf2vztxcjxe2ernf8m7ru5wvsqkdqxqyqsq7y540qmemqx3675pufewwmywsudzrpstjx3fd38c6d8uz4r4mgpqqqt2q2jjczxp2y6986zdqz3mr5jmhggmge3exc72vgw2kgr4gea2zgzhrz8q").unwrap();
    let record = record_ciphertext.decrypt(&view_key).unwrap();

    println!("{:?}", serde_json::json!(&record));
}

```
Build and run:
```shell
String("{\n  owner: aleo1snwe5h89dv6hv2q2pl3v8l9cweeuwrgejmlnwza6ndacygznlu9sjt8pgv.private,\n  gates: 1u64.private,\n  _nonce: 4447510634654730534613001085815220248957154008834207042015711498717088580021group.public\n}")
```

**Comment by ljedrz** [comment]
At first glance this looks like a deliberate design decision for pretty-printing purposes, but I'll double-check.

**Comment by ljedrz** [comment]
Confirmed, this is certainly deliberate; is there any reason why it would be causing issues?

**Comment by ilitteri** [comment]
> Confirmed, this is certainly deliberate; is there any reason why it would be causing issues?

Sorry, I forgot to add the motivation for this. This won't let records be consumed by other programs (I'll update the issue comment with this).

EDIT: client applications need to be able to consume the records as JSON, for example, applications using the wasm module, and currently the values are returned in this pretty printed format upon serialization.

**Comment by ljedrz** [comment]
The JSON standard [specifies](https://datatracker.ietf.org/doc/html/rfc8259#section-2) that whitespaces are insignificant:
> Insignificant whitespace is allowed before or after any of the six structural characters.

So this rather seems like an issue with the consumer.

**Comment by facundoolano** [comment]
is this the text that should be valid JSON?
``` 
"{\n  owner: aleo1snwe5h89dv6hv2q2pl3v8l9cweeuwrgejmlnwza6ndacygznlu9sjt8pgv.private,\n  gates: 1u64.private,\n  _nonce: 4447510634654730534613001085815220248957154008834207042015711498717088580021group.public\n}"
```

that one doesn't seem like it's going to parse reagardless of the whitespaces, it doesn't even have doublequotes in the field names.

**Comment by ljedrz** [comment]
The attached example is not a valid use of `serde_json::json` (which expects a JSON literal), but indeed, even with `println!("{}", serde_json::to_string(&record).unwrap())` this doesn't look right; I'll check the missing double-quotes, as this is invalid JSON :+1:.

**Comment by ljedrz** [comment]
There's a lot of custom serialization and parsing code involved; I'll need to first double-check if it is even _intended_ for this format to be JSON-compatible.

**Comment by ljedrz** [comment]
I've discussed this with @howardwu, and he said that the `Record` is **not** JSON-compatible, and it's not the intention, so this is not considered a bug, and any JSON interaction will have to be built additionally if need be.

**Comment by facundoolano** [comment]
I understand. Perhaps this ticket needs to be rephrased (or a separate ticket created instead) from "string serialization needs to be JSON compatible" to "APIs intended for programmatic consumption should support JSON instead of human-readable strings".

Otherwise, I see two problems if we only provide pretty printed records eg. in the REST endpoints:

1. It forces every client (e.g. every wallet implementation) to build their own parser for this pretty printed output. This is inconvenient but not such a big deal (it can be wrapped in a library and reused).
2. It's coupling programmatic consumers to the human readable representation of the record. If the representation changes it will inadvertedly break clients (or conversely the human readable representation won't be improved as to not break clients).

**Comment by ljedrz** [comment]
> separate ticket created instead

Sounds like a good idea :+1:.
