### ISSUE TITLE
[Proposal] Additional fees should not be optional for Execution Transactions

### ISSUE THREAD

**Issue by ilitteri** [AleoHQ/snarkVM#1131]
## 💥 Proposal

Originally this [issue](https://github.com/AleoHQ/snarkVM/issues/1076) proposed having fees be optional for all transactions. However, this poses a problem, because it opens the possibility for DDoS attacks on the network, as people can just submit transactions at no cost at all.

**Comment by howardwu** [comment]
The program itself is permitted (though currently not supported via necessary opcodes) to provide the fee in its transition already. This is why the additional fee is called an **additional** fee in our terminology.

We want to change this into a new Github issue that specifies the missing piece of moving credits from the `credits.aleo` program into any other program record. I'll go ahead and create an issue for this.
