### ISSUE TITLE
[Bug] Integer operations panic on underflow/overflow in Aleo Instructions

### ISSUE THREAD

**Issue by ilitteri** [AleoHQ/snarkVM#1133]
## 🐛 Bug Report

Integer operations panic on underflow/overflow in Aleo Instructions.

```
thread ‘main’ panicked at ‘Integer subtraction failed on: 0u64 and 1u64’, /Users/user/snarkVM/console/network/environment/src/environment.rs:62:9
```

## Steps to Reproduce

Send a transfer transaction with a record with no gates for an amount greater than zero.

## Expected Behavior

This error should be handled.

**Comment by ljedrz** [comment]
This currently happens by design, as the `halt` function is an explicit panic.

CC https://github.com/AleoHQ/snarkVM/issues/1096.
