### ISSUE TITLE
[Bug] REST API should use POST instead of GET if body required

### ISSUE THREAD

**Issue by evanmarshall** [AleoHQ/snarkVM#1146]
## 🐛 Bug Report

GET requests should not include a body: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET

The following requests incorrectly require a body on a GET request:
* GET /testnet3/statePath/{commitment}
* GET /testnet3/records/all
* GET /testnet3/records/spent
* GET /testnet3/records/unspent

Most javascript libraries won't let you set a body on a GET request making them incompatible with this API.
For example, axios doesn't let you put a body on a request. And the latest HTTP spec says that the body should always be ignored on a GET request.

See https://stackoverflow.com/questions/978061/http-get-with-request-body for a relevant discussion.

## Expected Behavior

If a body is required, use a POST request. A GET request can only be used if a request does not include a body and instead relies on url parms. 

It's possible to make these requests use the ViewKey as a url parameter but almost all RPC APIs use post requests for similar requests. See Solana's RPC API for an example: https://docs.solana.com/developing/clients/jsonrpc-api#example-2

**Comment by howardwu** [comment]
Duplicates AleoHQ/snarkOS#2010
