### ISSUE TITLE
[Bug] Rejected transitions are changing the finalize storage

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkVM#1548]
## 🐛 Bug Report

(This is a security bug, but as we are still on testnet, I'm reporting here)

snarkVM doesn't rollback changes when trying to execute the finalize operations of rejected executions.

## Steps to Reproduce

Already reproduced by someone on the live testnet with [this program](https://explorer.hamp.app/program?id=testing123.aleo). The first rejected transition changed the storage.

## Expected Behavior

Rejected transitions should not change the storage.

## Your Environment

Current testnet 3

## Details

I'm trying to write an interpreter of Aleo instructions to get the mapping values, until I encountered some issues on [this transition](https://explorer.hamp.app/transition?id=as1n9h7j45z239hjjgp6y0fgt24rzpva8ngkgxh35q0tqkpwv0yquys2rgnay) (I've skipped the [rejected transition](https://explorer.hamp.app/transition?id=as1mrh9nffvgd6e4jzyu4asvrlq84qgjwplpvsc7w5hvfkzwj8t5czq0eu4ac) as it should not affect the mapping storage).

Note the rejected transition has input of `10u8, 100u8`, so the second set of `add` operations will fail (tried to do `200u8 + 100u8`). However at this point, the last `set` command has stored the value `{count: 20u8, data: 200u8}` in the mapping, and the rejection of the transition didn't revert the storage changes.

In theory, the next accepted transition would start at a clean mapping storage, but there are only 2 finalize commands in that transaction, instead of 3 (come from `get.or_init` and two `set`s) (didn't show them on my explorer, so [raw block](https://vm.aleo.org/api/testnet3/block/14931) here). The `value_id` of the first command should verify it, as the value is `{count: 21u8, data: 202u8}`:

```rust
use snarkvm_console_program::{Field, Identifier, Literal, Plaintext, Value};
use snarkvm_console_program::FromStr;
use indexmap::IndexMap;
use snarkvm_console_network::{Network, Testnet3, ToBits};

fn main() {
    let value = Value::Plaintext(Plaintext::Struct(
        IndexMap::from_iter(
            vec![
                (
                    Identifier::from_str("count").unwrap(),
                    Plaintext::<Testnet3>::Literal(
                        Literal::<Testnet3>::from_str("21u8").unwrap(),
                        Default::default()
                    )
                ),
                (
                    Identifier::from_str("data").unwrap(),
                    Plaintext::<Testnet3>::Literal(
                        Literal::<Testnet3>::from_str("202u8").unwrap(),
                        Default::default()
                    )
                ),
            ]
                .into_iter(),
        ),
        Default::default(),
    ));
    println!("{:?}", value);
    let key_id = Field::<Testnet3>::from_str("6679816225070869277642545706246168867612829149463851804023197862921272508769field").unwrap();
    let value_id = <Testnet3 as Network>::hash_bhp1024(&(key_id, <Testnet3 as Network>::hash_bhp1024(&value.to_bits_le()).unwrap()).to_bits_le()).unwrap();
    println!("{:?}", value_id);
}
```
prints
```
{
  count: 21u8,
  data: 202u8
}
8429669485387850725534994500954642953635506875168032440768836063535078757651field
```
which matches the value in the block.

It seems the atomic batch is not working correctly, but I didn't figure out why it didn't rewind on failed `finalize()` calls.

**Comment by ljedrz** [comment]
I've looked into this and it seems to me like a logic bug at first glance; when `VM::atomic_finalize` is called and one of the `ConfirmedTransaction::{RejectedDeploy, RejectedExecute}` variants is encountered, we currently just continue looping over transactions without rewinding or aborting the batch, unless the deployment or execution fails (which doesn't occur with a test case I was running).

**Comment by HarukaMa** [comment]
Looks like the atomic batch implementation needs more fixes than I've thought. Some logs:

<details>
<summary>added some logs to atomic operations</summary>

```
is_atomic_in_progress: true
checkpointed at 0
checkpointed at 0
checkpointed at 0
checkpointed at 0
checkpointed at 0
Finalizing execution...
Finalizing transition for testing.aleo/compute...
Evaluating command: get.or_init entries[r0] r1 into r2;
is_atomic_in_progress: true
checkpointed at 0
checkpointed at 0
checkpointed at 0
checkpointed at 0
checkpointed at 0
insert key 7516096781094570372018704721619426996534694431359270142366331769380759037403field value {3268734687610189805944574172087519550226065542639808388362828179017304208302field: 2541159987936968819700103548824613608586128129614164250394575464168439851667field} into atomic batch
insert key 3268734687610189805944574172087519550226065542639808388362828179017304208302field value aleo1hmlu8jhcn8m8e8asv2k8zgl4w6ef8tdqc0u9h0l6gf3nx47qjv8qmtapv4 into atomic batch
insert key 3268734687610189805944574172087519550226065542639808388362828179017304208302field value 100u8 into atomic batch
success
Evaluating command: add r1 r2 into r3;
Evaluating command: set r3 into entries[r0];
is_atomic_in_progress: true
checkpointed at 0
checkpointed at 0
checkpointed at 1
key: 7516096781094570372018704721619426996534694431359270142366331769380759037403field, value: Some({3268734687610189805944574172087519550226065542639808388362828179017304208302field: 2541159987936968819700103548824613608586128129614164250394575464168439851667field})
checkpointed at 1
key: 3268734687610189805944574172087519550226065542639808388362828179017304208302field, value: Some(aleo1hmlu8jhcn8m8e8asv2k8zgl4w6ef8tdqc0u9h0l6gf3nx47qjv8qmtapv4)
checkpointed at 1
key: 3268734687610189805944574172087519550226065542639808388362828179017304208302field, value: Some(100u8)
insert key 7516096781094570372018704721619426996534694431359270142366331769380759037403field value {3268734687610189805944574172087519550226065542639808388362828179017304208302field: 6783834352755656135309990829348517289155956596187951163050622391353256210242field} into atomic batch
insert key 3268734687610189805944574172087519550226065542639808388362828179017304208302field value aleo1hmlu8jhcn8m8e8asv2k8zgl4w6ef8tdqc0u9h0l6gf3nx47qjv8qmtapv4 into atomic batch
insert key 3268734687610189805944574172087519550226065542639808388362828179017304208302field value 200u8 into atomic batch
success
Evaluating command: get entries[r0] into r4;
Evaluating command: add r4 r1 into r5;
thread 'vm::finalize::tests::test_rejected_transaction_should_not_update_storage' panicked at 'Integer addition failed on: 200u8 and 100u8', /home/mrx/src/snarkVM/console/network/environment/src/environment.rs:62:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
rewind, err 'finalize' failed to evaluate command (add r4 r1 into r5;)
before rewind: 0
after rewind: 0
before rewind: 0
after rewind: 0
before rewind: 1
key: 7516096781094570372018704721619426996534694431359270142366331769380759037403field, value: Some({3268734687610189805944574172087519550226065542639808388362828179017304208302field: 6783834352755656135309990829348517289155956596187951163050622391353256210242field})
after rewind: 1
key: 7516096781094570372018704721619426996534694431359270142366331769380759037403field, value: Some({3268734687610189805944574172087519550226065542639808388362828179017304208302field: 6783834352755656135309990829348517289155956596187951163050622391353256210242field})
before rewind: 1
key: 3268734687610189805944574172087519550226065542639808388362828179017304208302field, value: Some(aleo1hmlu8jhcn8m8e8asv2k8zgl4w6ef8tdqc0u9h0l6gf3nx47qjv8qmtapv4)
after rewind: 1
key: 3268734687610189805944574172087519550226065542639808388362828179017304208302field, value: Some(aleo1hmlu8jhcn8m8e8asv2k8zgl4w6ef8tdqc0u9h0l6gf3nx47qjv8qmtapv4)
before rewind: 1
key: 3268734687610189805944574172087519550226065542639808388362828179017304208302field, value: Some(200u8)
after rewind: 1
key: 3268734687610189805944574172087519550226065542639808388362828179017304208302field, value: Some(200u8)
```

</details>

First, the pending operations of an atomic batch is stored in an `IndexMap`, which would cause some operations unable to be reverted if they are operating on the same key. See the log above, the second `set` operation just overwritten the value `100u8` with `200u8`.

Second, the scope operation below:

https://github.com/AleoHQ/snarkVM/blob/6940b45eb96507ceb6c93b0a31475a5b9d1a348f/synthesizer/src/store/program/finalize.rs#L276-L285

will write a checkpoint, so everything before this call will not be able to be reverted. Even if the pending operations are stored properly in a `Vec`, the value `100u8` will still be already checkpointed by this block and unable to be reverted.

**Comment by howardwu** [comment]
Thanks for finding this. I did a trace through the logic and identified the issue.

It looks to be a simple fix. We need to add a new macro that does not perform the rollback operation on the lowest level.
