### ISSUE TITLE
[Bug] #1592 prevents nodes from syncing from scratch

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkVM#1620]
## 🐛 Bug Report

PR #1592 actually changed the consensus about how to run finalizers, and as the network was not reset, now we can't really resync the nodes; new nodes must start from snapshots instead.

## Steps to Reproduce

1. Attempt to resync the node

## Expected Behavior

Discord report:

```
WARN Failed to process block 14931: Failed to finalize transactions: Mismatch in finalize operations for an accepted execute
```

as snarkVM now behaves correctly, while the data in the block was generated with the incorrect logic.

## Your Environment

- Latest

**Comment by HarukaMa** [comment]
Actually, if we are resetting soonish, it might not worth it to reintroduce the old code to bring back the compatibility.

**Comment by Deiven** [comment]
Agreed

**Comment by web3deadline** [comment]
I met the same problem, maybe some new nodes are waiting for the issue fixed❤

**Comment by HarukaMa** [comment]
irrelevant as reset is coming soon
