### ISSUE TITLE
[Docs]  Error connecting to https://snarkvm.org (http works)

### ISSUE THREAD

**Issue by optimalbrew** [AleoHQ/snarkVM#167]
## 📚 Documentation

> _An error occurred during a connection to snarkvm.org. PR_END_OF_FILE_ERROR._ 

This is from Firefox. Similar error using Chrome. 

Link works (redirects back to repo) with http but not with https (currently points to).

**Comment by howardwu** [comment]
Thanks for bringing this up, the URL has been fixed.
