### ISSUE TITLE
[Bug/Security] shl Integer overflow on multiplication of two constants (i128 & u8)

### ISSUE THREAD

**Issue by pventuzelo** [AleoHQ/snarkVM#1678]
We (@fuzzinglabs) found an issue while fuzzing snarkvm code execution.

## Expected Behavior

The code should not crash, the code should return `-134737384471710954358520195933735485440`

## Your Environment

-  v0.4.3
-  rustc 1.72.0-nightly (371994e0d 2023-06-13)
-  Computer OS: Ubuntu 20.04

## Steps to Reproduce

Testing program:
``` rust
program foo.aleo;
function fuzz:
    shl 135585500719386414360360006185191384684i128 25u8 into r0;
    output r0 as i128.private;
```

Build and run:
``` sh
aleo run fuzz

⏳ Compiling 'foo.aleo'...

thread 'main' panicked at 'Integer overflow on multiplication of two constants', /home/cooper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/snarkvm-circuit-environment-0.11.7/src/circuit.rs:246:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Why it is wrong

The documentation (https://developer.aleo.org/aleo/opcodes#shl), tells us that the result of an operation with `i128` and `u8` as input gives us a `i128`

Using this Rust code, we reproduce the same operation:

```rust
fn main() {
    let val1: i128 = 135585500719386414360360006185191384684i128;
    let val2: u8 = 25u8;
    let res: Option<i128> = val1.checked_shl(val2 as u32); // shl 135585500719386414360360006185191384684i128 25u8 into r1;
    println!("Result: {:?}", res);
    println!("Result: {}", res.unwrap() as i128);
}
```

Executing this code, we have:

```sh
cargo run --release 
    Finished release [optimized] target(s) in 0.00s
     Running `target/release/aleo_debug_test`

Result: Some(-134737384471710954358520195933735485440)
Result: -134737384471710954358520195933735485440
```

We can see that there is no problem with the operation, it is still contained in an `i128`

**Comment by d0cd** [comment]
Discussed offline. Determined to *not* be an issue.
The semantics for `checked_shl` is different from that of Rust.
We opt for the the ISO/IEC standard for C which says that signed left shift is undefined by the standard if the left operand is negative or if the exact mathematical result (meant as left * 2**right) is not representable in the signed type.
The exact reference implementation is [here](https://github.com/AleoHQ/snarkVM/blob/a87e5152105671370489ddbed5892c307053af04/console/network/environment/src/traits/types.rs#L414).
