### ISSUE TITLE
[Proposal] Add `signature` type and/or `sign.verify`

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkVM#1730]
## 💥 Proposal

It could be useful to introduce a `signature` type to simplify and abstract storage of signatures in records/mappings.

It would also be beneficial to introduce a `sign.verify` opcode that is compatible with the Aleo signature type.

**Comment by kamranlatifch** [comment]
Hi,
I tried to use sign.verify in my aleo program that connects with worker file later. Its throuwing errors and No other details are to be found to solve the issue. On documentations no details are found according to this function.

Step 1...
I saved the aleo function in const.ts file
export const SIGVERIFY_PROGRAM = `
program signature_verification.aleo;
struct Message:
issuer as address;
subject as address;
dob as field;

function sign_verify:
input r0 as field.public;
input r1 as address.public;
input r2 as Message.public;
sign.verify r0 r1 r2 into r3;
output r0 as field.private;
`;
2. Step 2...
I have imported and stored in a variable
const response_Value = {
localProgram: SIGVERIFY_PROGRAM,
aleoFunction: "sign_verify",
};
3. Step 3...
Following is my function call
const response = await postMessagePromise(worker, {
type: "ALEO_EXECUTE_PROGRAM_LOCAL",
localProgram: response_Value.localProgram,
aleoFunction: response_Value.aleoFunction,
inputs: [
signature,
issuer,

    {
      issuer,
      subject,
      dob: `${dob}field`,
    },
  ],

  privateKey: account.to_string(),
});
4:Step 4

This is the error i am facing in console

Failed to parse string. Remaining invalid string is: "sign.verify r0 r1 r2 into r3;
output r0 as field.private;

-> I have treid add and other commands in aleo programme ,they are working fine. but on sign.verify i am unable to understand what is happening.

(Write what you expected to happen here)
I expect that a signature,address and message should pass on this pattern to sign.verify and i will get true or false.

Your Environment
1.72.1
Windows
