### ISSUE TITLE
[Bug] finalize method's loop can not use Mapping::get(xxxMap, i)'

### ISSUE THREAD

**Issue by AlexZhao6666** [AleoHQ/snarkVM#1747]
## 🐛 Bug Report

Using 'Mapping::get(ticketPurchaseMap, i)' in the for loop within the finalize method will result in an error "Critical bug in speculate: Cannot speculate on a fee transaction",move 'Mapping::get(ticketPurchaseMap, i)' to out of loop then it is ok.

## Steps to Reproduce

![1](https://github.com/AleoHQ/snarkVM/assets/136443781/1199bdec-b82b-441a-ad19-de352fabe116)

## Expected Behavior

(Write what you expected to happen here)
finaliz method can use Mapping::get(ticketPurchaseMap, i) in loop
## Your Environment

- 
snarkVM 0.12.6
- 
rust 1.70.0
- 
os 12.4

**Comment by ghostant-1017** [comment]
This issue should be fixed, check: https://github.com/AleoHQ/snarkVM/pull/1736.

**Comment by AlexZhao6666** [comment]
> This issue should be fixed, check: #1736.

the issue not fix now
https://github.com/AleoHQ/snarkVM/pull/1736 the pr not fix my issue.
my issue is :Using 'Mapping::get(ticketPurchaseMap, i)' in the for loop within the finalize method

**Comment by HarukaMa** [comment]
Basically, `if`s in finalizers should be compiled down to branch instructions. AFAIK this is planned.

**Comment by raychu86** [comment]
If I am reading your logic correctly, this is intended. 

Attempting to get a value from a mapping that doesn't contain your key will cause an error. 

Using mapping `get.or_use` is what you should be using if you do not know if a value exists, but want to set a default.

**Comment by HarukaMa** [comment]
Note: this is actually a Leo compiler issue, as the program compiles to Aleo instructions with side-effects that could not be ignored.
