### ISSUE TITLE
[Proposal] Change `TransitionID` algorithm to allow transitions with no input and output

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkVM#1761]
## 💥 Proposal

Currently the transition merkle tree only includes the input and output values, however if a transition doesn't have any of them, essentially we will have an empty tree, which results in duplicated transition IDs when the transition is called multiple times, even across different programs.

It seems there are some use cases, like calling the program to only mutate one field in a mapping, and no off-chain execution are needed. 

Adding tpk and/or tcm to the function tree could resolve that; however it seems currently that tree is used for acquiring state paths, so not sure if there will be undesired side-effects if irrelevant values are inserted. Feels wrong to stuff random things in it as well.

**Comment by howardwu** [comment]
Closing as this issue has been resolved. We now support transitions with no inputs or outputs.
