### ISSUE TITLE
[Bug] Add `finalize_operations` for `fee` in rejected deploy and rejected execute

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkVM#1914]
## 🐛 Bug Report

Add `finalize_operations` for `fee` in rejected deploy and rejected execute.

Currently, we do not store this, as that component in storage is used to hold the `rejected` blob.

**Comment by raychu86** [comment]
Closing with https://github.com/AleoNet/snarkVM/pull/2081
