### ISSUE TITLE
Important: Unable to build wasm-pack after adding snarkvm dependency[Bug]

### ISSUE THREAD

**Issue by kamranlatifch** [AleoHQ/snarkVM#2000]
## 🐛 Bug Report
error[E0433]: failed to resolve: use of undeclared crate or module `curl`
  --> C:\Users\kamra\.cargo\registry\src\index.crates.io-6f17d22bba15001f\snarkvm-parameters-0.14.6\src\macros.rs:72:28
   |
72 |             let mut easy = curl::easy::Easy::new();
   |                            ^^^^ use of undeclared crate or module `curl`

(Write your description here)

I have rust code that uses snarkvm crate. When i run command wasm-pack build this error is being occured so many times. Please Help me out to handle this.

I want if I have installed snarkvm and used seccessfully in my code with no error, than on wasm-pack build it should not create issues

## Your Environment

snarkvm = "0.14.6"
- 
- rustc 1.72.1 (d5c2e9c34 2023-09-13)
- 
-Windows

**Comment by iamalwaysuncomfortable** [comment]
SnarkVM supports `wasm` as a compilation target, but if you're building for `wasm` via `wasm-pack` you need to set the "wasm" feature flags in your Cargo.toml for your SnarkVM imports. From the information you've specified, it seems you're not using the wasm feature flag and thus experiencing the build errors above.

The following shows how you'd import SnarkVM such that you can build with `wasm-pack`.

```toml
### If importing the entire SnarkVM crate
[dependencies.snarkvm]
version = "0.14.6"
features = [ "wasm" ]
```

```toml
### If importing crates in the SnarkVM workspace
[dependencies.snarkvm-console]
version = "0.14.6"
features = [ "wasm" ]
```

Please try this to see if solves your issue. If it doesn't, can you please provide more information as to how you're using SnarkVM? Specifically, if you could share the sections of your Cargo.toml file in which you're importing SnarkVM, that would be helpful to help diagnose your issue.

**Comment by shaheer-teczon** [comment]
@iamalwaysuncomfortable Thank you for your response. Even though feature flag of wasm enabled. Still facing issue. Here is part of toml:

[lib]
crate-type = ["cdylib", "rlib"]



[features]
default = ["console_error_panic_hook"]

[dependencies]
snarkvm = { version = "0.14.6", features = ["wasm"] }
console_error_panic_hook = { version = "0.1.7", optional = true }
js-sys = "0.3.64"
rand = "0.8.5"
ring = "0.16.20"
wasm-bindgen = "0.2.87"
web-sys = "0.3.64"
indexmap = "2.0.0"
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

Error has changed to:

error[E0433]: failed to resolve: could not find `unix` in `os`
 --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/update.rs:4:14
  |
4 | use std::os::unix::fs::PermissionsExt;
  |              ^^^^ could not find `unix` in `os`

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
   --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/backends/gitea.rs:175:29
    |
175 |         let resp = reqwest::blocking::Client::new()
    |                             ^^^^^^^^ could not find `blocking` in `reqwest`
    |
help: consider importing one of these items
    |
4   + use crate::backends::gitea::reqwest::Client;
    |
4   + use reqwest::Client;
    |
help: if you import `Client`, refer to it directly
    |
175 -         let resp = reqwest::blocking::Client::new()
175 +         let resp = Client::new()
    |

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
   --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/backends/gitea.rs:480:29
    |
480 |         let resp = reqwest::blocking::Client::new()
    |                             ^^^^^^^^ could not find `blocking` in `reqwest`
    |
help: consider importing one of these items
    |
4   + use crate::backends::gitea::reqwest::Client;
    |
4   + use reqwest::Client;
    |
help: if you import `Client`, refer to it directly
    |
480 -         let resp = reqwest::blocking::Client::new()
480 +         let resp = Client::new()
    |

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
   --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/backends/gitea.rs:502:29
    |
502 |         let resp = reqwest::blocking::Client::new()
    |                             ^^^^^^^^ could not find `blocking` in `reqwest`
    |
help: consider importing one of these items
    |
4   + use crate::backends::gitea::reqwest::Client;
    |
4   + use reqwest::Client;
    |
help: if you import `Client`, refer to it directly
    |
502 -         let resp = reqwest::blocking::Client::new()
502 +         let resp = Client::new()
    |

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
   --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/backends/github.rs:177:29
    |
177 |         let resp = reqwest::blocking::Client::new()
    |                             ^^^^^^^^ could not find `blocking` in `reqwest`
    |
help: consider importing one of these items
    |
4   + use crate::backends::github::reqwest::Client;
    |
4   + use reqwest::Client;
    |
help: if you import `Client`, refer to it directly
    |
177 -         let resp = reqwest::blocking::Client::new()
177 +         let resp = Client::new()
    |

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
   --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/backends/github.rs:495:29
    |
495 |         let resp = reqwest::blocking::Client::new()
    |                             ^^^^^^^^ could not find `blocking` in `reqwest`
    |
help: consider importing one of these items
    |
4   + use crate::backends::github::reqwest::Client;
    |
4   + use reqwest::Client;
    |
help: if you import `Client`, refer to it directly
    |
495 -         let resp = reqwest::blocking::Client::new()
495 +         let resp = Client::new()
    |

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
   --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/backends/github.rs:522:29
    |
522 |         let resp = reqwest::blocking::Client::new()
    |                             ^^^^^^^^ could not find `blocking` in `reqwest`
    |
help: consider importing one of these items
    |
4   + use crate::backends::github::reqwest::Client;
    |
4   + use reqwest::Client;
    |
help: if you import `Client`, refer to it directly
    |
522 -         let resp = reqwest::blocking::Client::new()
522 +         let resp = Client::new()
    |

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
   --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/backends/gitlab.rs:172:29
    |
172 |         let resp = reqwest::blocking::Client::new()
    |                             ^^^^^^^^ could not find `blocking` in `reqwest`
    |
help: consider importing one of these items
    |
4   + use crate::backends::gitlab::reqwest::Client;
    |
4   + use reqwest::Client;
    |
help: if you import `Client`, refer to it directly
    |
172 -         let resp = reqwest::blocking::Client::new()
172 +         let resp = Client::new()
    |

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
   --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/backends/gitlab.rs:475:29
    |
475 |         let resp = reqwest::blocking::Client::new()
    |                             ^^^^^^^^ could not find `blocking` in `reqwest`
    |
help: consider importing one of these items
    |
4   + use crate::backends::gitlab::reqwest::Client;
    |
4   + use reqwest::Client;
    |
help: if you import `Client`, refer to it directly
    |
475 -         let resp = reqwest::blocking::Client::new()
475 +         let resp = Client::new()
    |

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
   --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/backends/gitlab.rs:500:29
    |
500 |         let resp = reqwest::blocking::Client::new()
    |                             ^^^^^^^^ could not find `blocking` in `reqwest`
    |
help: consider importing one of these items
    |
4   + use crate::backends::gitlab::reqwest::Client;
    |
4   + use reqwest::Client;
    |
help: if you import `Client`, refer to it directly
    |
500 -         let resp = reqwest::blocking::Client::new()
500 +         let resp = Client::new()
    |

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
   --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/backends/s3.rs:540:25
    |
540 |     let resp = reqwest::blocking::Client::new().get(&api_url).send()?;
    |                         ^^^^^^^^ could not find `blocking` in `reqwest`
    |
help: consider importing this struct
    |
4   + use reqwest::Client;
    |
help: if you import `Client`, refer to it directly
    |
540 -     let resp = reqwest::blocking::Client::new().get(&api_url).send()?;
540 +     let resp = Client::new().get(&api_url).send()?;
    |

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
   --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/lib.rs:685:29
    |
685 |         let resp = reqwest::blocking::Client::new()
    |                             ^^^^^^^^ could not find `blocking` in `reqwest`
    |
help: consider importing this struct
    |
132 + use reqwest::Client;
    |
help: if you import `Client`, refer to it directly
    |
685 -         let resp = reqwest::blocking::Client::new()
685 +         let resp = Client::new()
    |

error[E0599]: no method named `set_mode` found for struct `Permissions` in the current scope
   --> /home/sheikhsb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/self_update-0.37.0/src/update.rs:267:25
    |
267 |             permissions.set_mode(0o755);
    |                         ^^^^^^^^ method not found in `Permissions`



Kindly look into this matter. I think its coming from one of dependency of snarkvm. It will be great if you can provide some solution. Thank you.

**Comment by iamalwaysuncomfortable** [comment]
Which pieces of SnarkVM are you using? SnarkVM is a large dependency and you likely only need a small subset of it such as `snarkvm-console` or `snarkvm-synthesizer` (which each have their own `wasm` flags). Importing the entirety of SnarkVM can unnecessary bloat the size of your own executable. In a wasm context especially this can significantly increase the size of your wasm binary and slow page loading down significantly.

My guess is you likely only need `snarkvm-console`, `snarkvm-synthesizer`, or perhaps `snarkvm-utilities`. So please cosnsider changing the dependencies to only the ones you need - all of the major crates under SnarkVM can be found here: 

The imports would then look something like
```toml
[dependencies]
snarkvm_console = { version = "0.14.6", features = ["wasm"] }
snarkvm_synthesizer = { version = "0.14.6", features = ["wasm"] }
... all other dependencies
```

Please carefully inspect the actual pieces of SnarkVM you're using, use the approach above and see if this solves your issue.

**Comment by shaheer-teczon** [comment]
I do understand that concerns about size and sub modules. But my major concern is why i am not able use SnarkVM itself when using wasm-pack. Build is successful when using cargo but not when using wasm-pack. Is there any way i can import this or do i have to use all sub modules separately

**Comment by iamalwaysuncomfortable** [comment]
> I do understand that concerns about size and sub modules. But my major concern is why i am not able use SnarkVM itself when using wasm-pack. Build is successful when using cargo but not when using wasm-pack. Is there any way i can import this or do i have to use all sub modules separately

SnarkVM is a large multi-crate workspace project and there is some functionality in SnarkVM that explicitly doesn't support `wasm` such as the SnarkVM CLI. If you look at SnarkVM, we have all crates conditionally enabled a-la-carte with feature flags. However because Wasm requires very different conditions to operate correctly (i.e. no blocking, no direct system i/o, etc.) it is difficult to support it at the `workspace` level. Doing so would encourage extremely large `wasm` binary sizes as stated above.

> Is there any way i can import this or do i have to use all sub modules separately

Please import them separately, the Aleo SDK is a good example of how to do this correctly: https://github.com/AleoHQ/sdk/blob/testnet3/wasm/Cargo.toml
