### ISSUE TITLE
[Bug] snarkvm-algorithms-cuda unable to compile

### ISSUE THREAD

**Issue by AlexZhao6666** [AleoHQ/snarkVM#2010]
## 🐛 Bug Report
snarkvm-algorithms-cuda unable to compile successfully

## Steps to Reproduce

1. clone the respository
2. run "cargo build -p snarkvm-algorithms-cuda"

## Expected Behavior
compile successfully

## Your Environment

- testnet3 branch
- 1.71.1
- Ubuntu 20.04.5 LTS

## Current Error
root@office-ubuntu:~/snarkVM# cargo build snarkvm-algorithms-cuda
error: unexpected argument 'snarkvm-algorithms-cuda' found

Usage: cargo build [OPTIONS]

For more information, try '--help'.
root@office-ubuntu:~/snarkVM# cargo build -p snarkvm-algorithms-cuda
   Compiling snarkvm-algorithms-cuda v0.14.6 (/root/snarkVM/algorithms/cuda)
The following warnings were emitted during compilation:

warning: cuda/snarkvm.cu(275): error: identifier "vec_t" is undefined
warning:                       ret = msm.invoke(partial_sums[i], vec_t<affine_t>{pts, sz},
warning:                                                         ^
warning: 
warning: cuda/snarkvm.cu(275): error: type name is not allowed
warning:                       ret = msm.invoke(partial_sums[i], vec_t<affine_t>{pts, sz},
warning:                                                               ^
warning: 
warning: cuda/snarkvm.cu(275): error: expected an expression
warning:                       ret = msm.invoke(partial_sums[i], vec_t<affine_t>{pts, sz},
warning:                                                                        ^
warning: 
warning: 3 errors detected in the compilation of "cuda/snarkvm_api.cu".

error: failed to run custom build command for `snarkvm-algorithms-cuda v0.14.6 (/root/snarkVM/algorithms/cuda)`

Caused by:
  process didn't exit successfully: `/root/snarkVM/target/debug/build/snarkvm-algorithms-cuda-654ca39e7560ec30/build-script-build` (exit status: 1)
  --- stdout
  Enabling ADX because it was detected on the host
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("adx,aes,avx,avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,pclmulqdq,popcnt,rdrand,rdseed,sse,sse2,sse3,sse4.1,sse4.2,ssse3,xsave,xsavec,xsaveopt,xsaves")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("adx,aes,avx,avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,pclmulqdq,popcnt,rdrand,rdseed,sse,sse2,sse3,sse4.1,sse4.2,ssse3,xsave,xsavec,xsaveopt,xsaves")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("adx,aes,avx,avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,pclmulqdq,popcnt,rdrand,rdseed,sse,sse2,sse3,sse4.1,sse4.2,ssse3,xsave,xsavec,xsaveopt,xsaves")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("adx,aes,avx,avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,pclmulqdq,popcnt,rdrand,rdseed,sse,sse2,sse3,sse4.1,sse4.2,ssse3,xsave,xsavec,xsaveopt,xsaves")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-I" "/root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/blst-0.3.11/blst/src" "-Wall" "-Wextra" "-mno-avx" "-fno-builtin" "-Wno-unused-command-line-argument" "-D__ADX__" "-o" "/root/snarkVM/target/debug/build/snarkvm-algorithms-cuda-e46416929d75b88d/out/src/lib.o" "-c" "src/lib.c"
  exit status: 0
  cargo:rerun-if-env-changed=AR_x86_64-unknown-linux-gnu
  AR_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=AR_x86_64_unknown_linux_gnu
  AR_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64-unknown-linux-gnu
  ARFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64_unknown_linux_gnu
  ARFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  running: ZERO_AR_DATE="1" "ar" "cq" "/root/snarkVM/target/debug/build/snarkvm-algorithms-cuda-e46416929d75b88d/out/libblst_msm.a" "/root/snarkVM/target/debug/build/snarkvm-algorithms-cuda-e46416929d75b88d/out/src/lib.o"
  exit status: 0
  running: "ar" "s" "/root/snarkVM/target/debug/build/snarkvm-algorithms-cuda-e46416929d75b88d/out/libblst_msm.a"
  exit status: 0
  cargo:rustc-link-lib=static=blst_msm
  cargo:rustc-link-search=native=/root/snarkVM/target/debug/build/snarkvm-algorithms-cuda-e46416929d75b88d/out
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CXX_x86_64-unknown-linux-gnu
  CXX_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXX_x86_64_unknown_linux_gnu
  CXX_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=NVCC_x86_64-unknown-linux-gnu
  NVCC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=NVCC_x86_64_unknown_linux_gnu
  NVCC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_NVCC
  HOST_NVCC = None
  cargo:rerun-if-env-changed=NVCC
  NVCC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("adx,aes,avx,avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,pclmulqdq,popcnt,rdrand,rdseed,sse,sse2,sse3,sse4.1,sse4.2,ssse3,xsave,xsavec,xsaveopt,xsaves")
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  running: "nvcc" "-ccbin=c++" "-Xcompiler" "-O3" "-Xcompiler" "-ffunction-sections" "-Xcompiler" "-fdata-sections" "-Xcompiler" "-fPIC" "-G" "-Xcompiler" "-gdwarf-4" "-Xcompiler" "-fno-omit-frame-pointer" "-m64" "-I" "/root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/blst-0.3.11/blst/src" "-I" "/root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.5/sppark" "-Xcompiler" "-Wall" "-Xcompiler" "-Wextra" "-g" "-arch=sm_70" "-maxrregcount=255" "-Xcompiler" "-Wno-unused-function" "-Xcompiler" "-Wno-subobject-linkage" "-DTAKE_RESPONSIBILITY_FOR_ERROR_MESSAGE" "-DFEATURE_BLS12_377" "-D__ADX__" "-o" "/root/snarkVM/target/debug/build/snarkvm-algorithms-cuda-e46416929d75b88d/out/cuda/snarkvm_api.o" "-c" "cuda/snarkvm_api.cu"
  cargo:warning=cuda/snarkvm.cu(275): error: identifier "vec_t" is undefined

  cargo:warning=                      ret = msm.invoke(partial_sums[i], vec_t<affine_t>{pts, sz},

  cargo:warning=                                                        ^

  cargo:warning=

  cargo:warning=cuda/snarkvm.cu(275): error: type name is not allowed

  cargo:warning=                      ret = msm.invoke(partial_sums[i], vec_t<affine_t>{pts, sz},

  cargo:warning=                                                              ^

  cargo:warning=

  cargo:warning=cuda/snarkvm.cu(275): error: expected an expression

  cargo:warning=                      ret = msm.invoke(partial_sums[i], vec_t<affine_t>{pts, sz},

  cargo:warning=                                                                       ^

  cargo:warning=

  cargo:warning=3 errors detected in the compilation of "cuda/snarkvm_api.cu".

  exit status: 2

  --- stderr

  error occurred: Command "nvcc" "-ccbin=c++" "-Xcompiler" "-O3" "-Xcompiler" "-ffunction-sections" "-Xcompiler" "-fdata-sections" "-Xcompiler" "-fPIC" "-G" "-Xcompiler" "-gdwarf-4" "-Xcompiler" "-fno-omit-frame-pointer" "-m64" "-I" "/root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/blst-0.3.11/blst/src" "-I" "/root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.5/sppark" "-Xcompiler" "-Wall" "-Xcompiler" "-Wextra" "-g" "-arch=sm_70" "-maxrregcount=255" "-Xcompiler" "-Wno-unused-function" "-Xcompiler" "-Wno-subobject-linkage" "-DTAKE_RESPONSIBILITY_FOR_ERROR_MESSAGE" "-DFEATURE_BLS12_377" "-D__ADX__" "-o" "/root/snarkVM/target/debug/build/snarkvm-algorithms-cuda-e46416929d75b88d/out/cuda/snarkvm_api.o" "-c" "cuda/snarkvm_api.cu" with args "nvcc" did not execute successfully (status code exit status: 2).

**Comment by AlexZhao6666** [comment]
type error, this should fix it, see PR #2011

**Comment by howardwu** [comment]
Closing as fix was merged.
