### ISSUE TITLE
[Feature] Fixed path for snarkVM parameters

### ISSUE THREAD

**Issue by zosorock** [AleoHQ/snarkVM#206]
## 🚀 Feature

It would be amazing if we could move the location where the parameters are store to a fixed location. Right now when I start it, it points to
`~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkvm-parameters-0.5.4/src/testnet1/`

Could it be something like `~/.snarkvm/parameters`?

## Motivation

That would help the work done with persistent storage. Right now it seems to very with every release it changes so we cannot mount persistent storage in that path. We have to run it, figure out what the path will be, and build again with that directory as mount point.

**Comment by howardwu** [comment]
@Protryon what's your opinion on this?

From my perspective, it seems to make sense to put parameters in `~/.snarkvm/parameters`, however for developers working on snarkVM this results in saving 600MBs of parameter data to a folder they may be unaware of.

**Comment by howardwu** [comment]
There is separately a question for the WASM context what the best convention for loading parameters is.

**Comment by mengsuenyan** [comment]
@howardwu 

May be this is a bug?  when the relative path and the absolute path doesn't exist, the parameter can never be stored locally.

https://github.com/AleoHQ/snarkVM/issues/193

```rust
// load_bytes() -> store_bytes

            fn store_bytes(
                buffer: &[u8],
                relative_path: &std::path::Path,
                absolute_path: &std::path::Path,
                file_path: &std::path::Path,
            ) -> Result<(), crate::errors::ParameterError> {
                use snarkvm_utilities::Write;

                println!("{} - Storing parameters ({:?})", module_path!(), file_path);
                // Attempt to write the parameter buffer to a file.
                if let Ok(mut file) = std::fs::File::create(relative_path) {
                    file.write_all(&buffer)?;
                } else if let Ok(mut file) = std::fs::File::create(absolute_path) {
                    file.write_all(&buffer)?;
                } else {
                  .....
                }
                Ok(())
            }
```

**Comment by depool-live** [comment]
where I can download inner_snark_pk-68eebd0.params?
node crash after ~30% of downloading

**Comment by raychu86** [comment]
Parameters are currently stored in `.aleo/resources/ `
