### ISSUE TITLE
[Bug] Rejected transactions don't have `finalize` object

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkVM#2084]
## 🐛 Bug Report

`AcceptedExecute` and `AcceptedDeploy` have `finalize` which stores all `FinalizeOperations`, but `RejectedExecute` and `RejectedDeploy` currently don't have that field.

That field was indeed not required before; however, we now have `public_fee`, so even if a transaction is rejected, there might still be a finalize operation to execute to remove the fee from the `account` mapping.

By the way, finalize operations created by `public_fee` are stored in the `finalize` field for accepted transactions.

I assumed the fee is indeed paid. Didn't check if this is actually the case.

## Steps to Reproduce

Block 41140 has a rejected transaction which has paid the fee with `public_fee`.

## Expected Behavior

All finalize operations created by transactions should be recorded in the block.

## Your Environment

- 
- 
-

**Comment by HarukaMa** [comment]
Does #2081 cover this?

EDIT: Yes it does, saw [d8d8776](https://github.com/AleoHQ/snarkVM/commit/d8d87767e6bbc258321ce74d6152d74acc13c554)

**Comment by howardwu** [comment]
I just updated that PR with ccfe9d5, which will ensure the Rejected types store the finalize operations with their confirmed transaction directly for better visibility.
