### ISSUE TITLE
[Proposal] Use sort-by-point-name in poly-commit

### ISSUE THREAD

**Issue by weikengchen** [AleoHQ/snarkVM#210]
## 💥 Proposal

This is a follow-up of the PR. 

There is another issue causing the `marlin_test_nested_snark` test to fail. It requires big-picture changes to completely fix this one--both native and constraints must sort points by names. 

In snarkVM, it follows an older version's poly-commit implementation. It sorts the points by values so that it matches the native order. 
https://github.com/AleoHQ/snarkVM/blob/master/polycommit/src/marlin_pc/gadgets/marlin_kzg10.rs#L155

However, this is indeed problematic. In fact, the upstream poly-commit now intentionally sorts the points by names, both in the gadget and the native version. As you can see in the native batch_open, it is changed accordingly.
https://github.com/arkworks-rs/poly-commit/blob/constraints/src/marlin/marlin_pc/constraints.rs#L957
https://github.com/arkworks-rs/poly-commit/blob/master/src/marlin/marlin_pc/mod.rs#L490

Why sort by names? 

Because different proofs will have points being in different orders. Sometimes, alpha is smaller than beta. In other proofs, beta is smaller than alpha. Recalling that our circuit needs to be data-independent, and here, challenge-independent, to make sure that it can verify different proofs. 

Therefore, in arkworks-rs, we intentionally make the order by explicit names "alpha", "beta", so that it is not sensitive to specific values.

This also resolves Raymond's notes on the to-do about sorting the points by values but having trouble handling the setup mode. The sort-by-point-name approach is designed specifically to avoid leaving proof-specific things into the setup.

**Comment by raychu86** [comment]
RIght. This also solves the potential `AssignmentMissing` issue during `point.value.value()?` https://github.com/AleoHQ/snarkVM/blob/bd37c5e0ed890ec2af13eefa9d9774f2e2e7a12c/polycommit/src/marlin_pc/gadgets/marlin_kzg10.rs#L159 will panic due do an unassigned variable in the setup phase

**Comment by weikengchen** [comment]
Add a note to this: It is possible that we don't need the big-picture change, as just changing the code to be sort-by-point-name immediately fixes the test, though it has a side effect that all the other tests fail (I don't know why...). I will look into it in more detail.

Recently, arkworks-rs poly-commit may have some refactoring and the constraint code will be significantly cleaned up and improved. We may integrate those changes after it is done (likely in one month).

**Comment by weikengchen** [comment]
This issue has been fixed.
