### ISSUE TITLE
[Proposal] Introduce low level call to arbitrary program with arbitrary data.

### ISSUE THREAD

**Issue by zklim** [AleoHQ/snarkVM#2104]
## 💥 Proposal

Introduce low level call to arbitrary program with arbitrary data instead of supporting only predetermine programs imports / interfaces. This opens up a lot of use cases like proxies, upgradable programs and even autonomous worlds. Not sure if Leo / Aleo Instruction currently supports this.

**Comment by vicsn** [comment]
Thank you for sharing the proposal! In general such radical proposals might be better suited for this repo, where we invite you to add more examples, documentation and context - https://github.com/AleoHQ/ARCs/

Currently the compiler requires everything to be defined with types and programs, somewhat similar to compiled languages in general, so such a change is likely not possible. But if you have a specific usecase or problem in mind, we can walk backwards from there to see what we need to support.
