### ISSUE TITLE
Generalize FFT infrastructure to work with group elements as well [Feature]

### ISSUE THREAD

**Issue by emmorais** [AleoHQ/snarkVM#212]
## 🚀 Feature

In [aleo-setup](https://github.com/AleoHQ/aleo-setup/) repository, in order to complete migration from zexe algebra to snarkVM algebra, we need to extend the FFT infrastructure to work with group elements, as was done in this following [PR](https://github.com/arkworks-rs/snark/pull/117/commits/a58883463b355fef1ee2a5b495fe2c9dff130f4e). 

## Motivation

In branch `replaced-zexe-algebra-with-snark-vm` of [aleo-setup](https://github.com/AleoHQ/aleo-setup/) repository, FFT receives as input a set of elliptic curve points. Therefore this branch doesn't build. 

## Implementation

To extend the FFT infrastructure, it is necessary to:

* Include `DomainCoeff` trait, as shown in the [PR](https://github.com/arkworks-rs/snark/pull/117/commits/a58883463b355fef1ee2a5b495fe2c9dff130f4e) (line 47 from ff-fft/src/domain.rs)
* Include `EvaluationDomain` trait
* Adapt the elliptic curve group accordingly
* Adapt the test as  in the [PR](https://github.com/arkworks-rs/snark/pull/117/commits/a58883463b355fef1ee2a5b495fe2c9dff130f4e) (line 9 from ff-fft/src/test.rs)

**Comment by apruden2008** [comment]
@howardwu @raychu86 would be great if you guys could take a look at this (and the associated PR #213) so we can complete migration of setup to snarkVM

**Comment by howardwu** [comment]
#217
