### ISSUE TITLE
[Bug] Panic (index out of range) when trying to skip_leading_zeros_and_convert_to_bigints a zero polynomial (with all coefficients equal to 0, not empty)

### ISSUE THREAD

**Issue by pventuzelo** [AleoHQ/snarkVM#2121]
# Panic (index out of range) when trying to skip_leading_zeros_and_convert_to_bigints a zero polynomial (with all coefficients equal to 0, not empty)
​
We (@fuzzinglabs) found an index out of range in the skip_leading_zeros_and_convert_to_bigints function, used by commit, making the library crash:
​
```sh
thread 'main' panicked at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/kzg10/mod.rs:462:23
```
​
## Your Environment
​
- rustc 1.73.0 (cc66ad468 2023-10-03)
- Ubuntu 23.04
​
## Steps to reproduce
​
Download:
​
``` sh
git clone https://github.com/AleoHQ/snarkVM.git
```
​
Testing program:
​
***main.rs***:
​
``` rust
use snarkvm_algorithms::fft::polynomial::*;
use snarkvm_curves::bls12_377::{Fr};
use snarkvm_algorithms::polycommit::kzg10::*;
use snarkvm_utilities::rand::TestRng;
use rand::Rng;
​
fn main() {
    let rng = &mut TestRng::default();

    let p1 = DensePolynomial::<Fr>::rand(rng.gen_range(0..10), rng); //random sample a polynomial of degree less than 10

    let p = &p1 - &p1; //create a polynomial with all coefficients to 0 (important that the vector of coefficients is not empty, but filled with 0)
    
    let (number_of_0,p_without_0) = skip_leading_zeros_and_convert_to_bigints(&p); //error
}
​
```
​
***Cargo.toml***:
​
```
[package]
name = "tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
snarkvm = { path = "../snarkVM" }
snarkvm-algorithms = { path = "../snarkVM/algorithms" }
snarkvm-curves = { path = "../snarkVM/curves" }
snarkvm-utilities = "0.15.4"
​
```
​
Build and run:
​
``` sh
cargo build
cargo run
```
​
## Root cause
​https://github.com/AleoHQ/snarkVM/blob/637e734e19f4b852daae683df4fd36bb17b7fcb9/algorithms/src/polycommit/kzg10/mod.rs#L455C9-L455C92
## Detailed behavior (RUST_BACKTRACE=1)
​
``` sh
thread 'main' panicked at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/kzg10/mod.rs:462:23:
index out of bounds: the len is 1 but the index is 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:162:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/slice/index.rs:261:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/mod.rs:2675:9
   6: snarkvm_algorithms::polycommit::kzg10::skip_leading_zeros_and_convert_to_bigints
             at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/kzg10/mod.rs:462:23
   7: tests::polynomial_null
             at ./src/main.rs:19:37
   8: tests::main
             at ./src/main.rs:120:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ljedrz** [comment]
I've looked at it, but I'm not sure if all of the `coeffs` may be `0`, or rather what should happen in that situation (which is what would trigger this bug). In any case, one that's decided, the fix is simple.

**Comment by vicsn** [comment]
> I've looked at it, but I'm not sure if all of the coeffs may be 0, or rather what should happen in that situation (which is what would trigger this bug). In any case, one that's decided, the fix is simple.

Without further context, leading zeros are meaningless and may be trimmed. NCC highlighted this issue already which we'll fix soon™️: we should trim the leading zeros as part of the arithmetic operation (in the example above `let p = &p1 - &p1`).

If you already have a fix in mind, want to go ahead and create the PR? :)

**Comment by RonanThoraval** [comment]
> > I've looked at it, but I'm not sure if all of the coeffs may be 0, or rather what should happen in that situation (which is what would trigger this bug). In any case, one that's decided, the fix is simple.
> 
> Without further context, leading zeros are meaningless and may be trimmed. NCC highlighted this issue already which we'll fix soon™️: we should trim the leading zeros as part of the arithmetic operation (in the example above `let p = &p1 - &p1`).
> 
> If you already have a fix in mind, want to go ahead and create the PR? :)

Yes, If I may, I think you can replace the ```p.coeffs.is_empty()``` by ```p.is_zero()```, or place the check before accessing the element (in the ```while```), or, as you said, you can use ```from_coefficients_vec``` or ```from_coefficients_slice``` to create a zero polynomial represented by an empty vector instead of being filled with 0s.

**Comment by vicsn** [comment]
Correction: leading zeros are okay, *trailing* zeroes should be trimmed. The fix in the PR is still fine.
