### ISSUE TITLE
[Bug] Speculation accepts multiple deploy txs with same program name in one block

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkVM#2202]
## 🐛 Bug Report

If a block contains multiple deployment transactions which have duplicated program names, all transactions will be accepted, and only the last one will be considered "canonical" as it will be the last one to be processed.

This doesn't happen if there are mapping name conflicts, as that will be caught by `initialize_mapping` function.

For examples:

1. `at15rq5mg88ex6mwy4wjjcn2zv655r4qcp6gn30jfkf5nrmngfljuyskxvacl` / `at1gwxfwfuztn65emsd4wcjqncesfermmtwp9fua2aehzu6yj0hasxs5jqg2s`
2. `at19c4j4jfh0kezksfllc3pvs0lka60mkpzxdzq2grvmgqnaxawpuzsg7klcw` / `at1aapu0g0p8kn76sd2u8jr7p4rsmy584yq5ufzur9897urrkqeasrs6qr2gz`

For an incomplete list, see https://gist.github.com/HarukaMa/2db529ce61cbe4ef49b3a632889857af

I never got an official acknowledgement of this bug so opening an issue to track it.

I believe this is not a security bug.

## Steps to Reproduce

Probably by trying to deploy one program multiple times within one block.

## Expected Behavior

Only one transaction should be accepted.

## Your Environment

N/A

**Comment by ghostant-1017** [comment]
It's indeed another situation need to be considered.
Similar to: https://github.com/AleoHQ/snarkOS/pull/2852

**Comment by HarukaMa** [comment]
should be fixed in #2211
