### ISSUE TITLE
[Bug] Incorrect assertion failure in polynomial `degree` function due to leading coefficient equal to 0 after `DensePolynomial` subtraction operation

### ISSUE THREAD

**Issue by pventuzelo** [AleoHQ/snarkVM#2206]
# Incorrect assertion failure in polynomial `degree` function due to leading coefficient equal to 0 after `DensePolynomial` subtraction operation

**Author(s):** Ronan Thoraval from [@Fuzzinglabs](https://github.com/FuzzingLabs/)
**Date:** 24/11/2023

## ****Executive Summary****

Call the [`degree()`](https://github.com/AleoHQ/snarkVM/blob/c620cc4a89bcd81e9de07e827886a2a57e4375e6/algorithms/src/fft/polynomial/dense.rs#L88) function on a polynomial with a leading coefficient equal to 0 leads to the failure of an assertion which checks that the first coefficient is not 0 (except if the polynomial is zero), and so panics.

We can have such a polynomial by subtracting two different polynomials with the same degree and the same leading coefficient. We can't create directly this polynomial with the [`from_coefficients_vec()`](https://github.com/AleoHQ/snarkVM/blob/c620cc4a89bcd81e9de07e827886a2a57e4375e6/algorithms/src/fft/polynomial/dense.rs#L76) function, because it removes all the leading zeros, which is not necessarily done with the subtraction (and others) operation(s).

## Vulnerability Details

- **Severity:** High

## Environment

- **Compiler Version:** cargo 1.73.0 (9c4383fb5 2023-08-26)
- **Distro Version:** Ubuntu 23.04

## Steps to Reproduce

``` rust
use rand::Rng;
use snarkvm_algorithms::fft::polynomial::*;
use snarkvm_curves::bls12_377::Fr;
use snarkvm_utilities::rand::TestRng;
use snarkvm_fields::Zero;

fn main(){

    let rng = &mut TestRng::default();

    let p1 = DensePolynomial::<Fr>::rand(rng.gen_range(1..10), rng);

    // p2 = leading_coeff_p1 * x^deg_p1
    let mut coeffs = vec![Fr::zero(); p1.degree()+1];
    coeffs[p1.degree()] = *p1.coeffs().last().unwrap();
    let p2 = DensePolynomial::<Fr>::from_coefficients_vec(coeffs) ;

    let p = &p1 - &p2;

    let _ = p.degree();
}
```

## Root Cause Analysis

We constructed a polynomial $p$ of degree $d$ represented by the vector $(c_0,...,c_{d-1},0)$, with $c_i$ the coefficient of $x^i$.
The [`assert`](https://github.com/AleoHQ/snarkVM/blob/c620cc4a89bcd81e9de07e827886a2a57e4375e6/algorithms/src/fft/polynomial/dense.rs#L92) instruction checks that the leading coefficient of the polynomial is not 0, which is the case in our situation, and so it panics.

The key point is that there is the possibility to construct a polynomial with a leading coefficient equal to 0, which is supposedly not possible.

## Detailed Behavior

``` sh
thread 'main' panicked at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/fft/polynomial/dense.rs:92:13:
assertion failed: self.coeffs.last().map_or(false, |coeff| !coeff.is_zero())
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: snarkvm_algorithms::fft::polynomial::dense::DensePolynomial<F>::degree
             at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/fft/polynomial/dense.rs:92:13
   4: tests::polynomial_null_degree
             at ./src/main.rs:43:13
   5: tests::main
             at ./src/main.rs:461:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5     
```

## Recommendations

1. Remove the assert and replace it with a line that counts the number of leading zeros. Then at the following line, subtract this count:

From
``` rust
} else {
            assert!(self.coeffs.last().map_or(false, |coeff| !coeff.is_zero()));
            self.coeffs.len() - 1
        }
```

To 
``` rust
} else {
            let num_leading_zeros = self.coeffs.iter().rev().take_while(|c| c.is_zero()).count();
            self.coeffs.len() - 1 - num_leading_zeros
        }
```
2. In the operation functions, remove the leading zeros at the end (like done in [the last `else` of the sub](https://github.com/AleoHQ/snarkVM/blob/c620cc4a89bcd81e9de07e827886a2a57e4375e6/algorithms/src/fft/polynomial/dense.rs#L300) operation).

**Comment by ljedrz** [comment]
I tried reproducing it with `0f324520e22d9af9d855be41893355f41a1efc63` (current `testnet3`), but I was unable to trigger a panic in both `release` and `debug` modes; it's likely that it has recently been fixed.

**Comment by RonanThoraval** [comment]
Yes you are right, the problem has already been fixed !
