### ISSUE TITLE
[Bug]Speculation accepts multiple deploy txs with same program name in one block

### ISSUE THREAD

**Issue by babulsahoo20** [AleoHQ/snarkVM#2221]
🐛 Bug Report
If a block contains multiple deployment transactions which have duplicated program names, all transactions will be accepted, and only the last one will be considered "canonical" as it will be the last one to be processed.

This doesn't happen if there are mapping name conflicts, as that will be caught by initialize_mapping function.

For examples:

at15rq5mg88ex6mwy4wjjcn2zv655r4qcp6gn30jfkf5nrmngfljuyskxvacl / at1gwxfwfuztn65emsd4wcjqncesfermmtwp9fua2aehzu6yj0hasxs5jqg2s
at19c4j4jfh0kezksfllc3pvs0lka60mkpzxdzq2grvmgqnaxawpuzsg7klcw / at1aapu0g0p8kn76sd2u8jr7p4rsmy584yq5ufzur9897urrkqeasrs6qr2gz

I never got an official acknowledgement of this bug so opening an issue to track it.

I believe this is not a security bug.

Steps to Reproduce
Probably by trying to deploy one program multiple times within one block.

Expected Behavior
Only one transaction should be accepted.

Your Environment
N/A

**Comment by HarukaMa** [comment]
I never thought we would have this kind of behavior here. This is a literal copy-paste from #2202 with unknown intention.

**Comment by vicsn** [comment]
Thank you for flagging Haruka
