### ISSUE TITLE
[Feature]  make an import private key option when we install aleo web extension

### ISSUE THREAD

**Issue by wnhedaxx** [AleoHQ/snarkVM#2244]
## 🚀 Feature

(Write your description here)

## Motivation

(

## Implementation

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by HarukaMa** [comment]
If you are referring to the Leo Wallet, submit your feature request here instead: https://discord.gg/MW8xJyMuwN .

**Comment by raychu86** [comment]
Closing this issue, as it is not relevant to snarkVM.
