### ISSUE TITLE
[Bug] String Type random test is flaky

### ISSUE THREAD

**Issue by vicsn** [AleoHQ/snarkVM#2269]
## Steps to Reproduce

`cd console/types/string && cargo test test_random`
Change `ITERATIONS` to 1000 to make it very likely.

## Expected Behavior

The test should only fail with negligible probability.

## Your Environment

snarkVM v0.16.15
cargo 1.71.1
macOS

**Comment by ljedrz** [comment]
Cc https://github.com/AleoHQ/snarkVM/issues/986
