### ISSUE TITLE
[Feature] Switch to hash to curve

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkVM#228]
## 🚀 Feature

In preparing for production, we need to switch the generators and parameters for a number of (snarkvm-)algorithms to a hash to curve implementation.

To do the switch, we will use a hash function such as Blake2s on a checkpointed string to compute a digest that is mapped to a corresponding field element, and used as the x-coordinate to derive the y-coordinate for an affine point on the curve.

This will involve adding an implementation of `from_random_bytes` or equivalent into our curve templates.

By making this update, an added benefit will be a simplification of our function signatures for higher-level objects, such as in our account private key, view key, and address for example.

**Comment by Pratyush** [comment]
@kobigurk I think you had some experience with doing this for Plumo, right?

**Comment by kobigurk** [comment]
Yes! We have nice gadgets that help with this. I'll send some links later.

**Comment by howardwu** [comment]
#241

**Comment by howardwu** [comment]
#251
