### ISSUE TITLE
[Bug] Flaky CI test `Failed to download powers ...`

### ISSUE THREAD

**Issue by vicsn** [AleoHQ/snarkVM#2286]
## 🐛 Bug Report

When running CI on https://github.com/AleoHQ/snarkVM/pull/2285 , the following failed:
```
thread 'package::clean::tests::test_clean_with_import' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute instruction (call token.aleo/transfer r0 r1 r2 into r3 r4;): Failed to download powers for degree 131072: Expected size of 6291464, found size of 0', vm/package/clean.rs:94:44
```

And I think I've seen CI tests fail on `Failed to download powers ...` before. Locally it succeeds.

## Your Environment

- Docker / [2X-Large](https://circleci.com/docs/2.0/configuration-reference/#resourceclass)
- cimg/rust:1.71.1
- Build-agent version 1.0.215493-04b71a14

**Comment by howardwu** [comment]
To our knowledge, this is an S3 issue. There have been periods whether the AWS region hosting this S3 bucket has instability or outages. I don't believe this is a variable we can control from our side of things.
