### ISSUE TITLE
Where can I find BLS12-377/BW6-761 universal SRS files?

### ISSUE THREAD

**Issue by readygo67** [AleoHQ/snarkVM#2325]
aztec  upload their srs at (https://aztec-ignition.s3.eu-west-2.amazonaws.com/index.html), I wonder where can I find Aleo's BLS12-377/BW6-761 universal SRS files.

**Comment by damons** [comment]
This isn't really a bug, so, closing this.  We have a public bucket for it somewhere.  If I find it, I'll update here, but it's public.

**Comment by raychu86** [comment]
Access to the SRS can be found here - https://github.com/AleoNet/snarkVM/blob/mainnet-staging/parameters/src/mainnet/mod.rs#L24-L74
