### ISSUE TITLE
[Proposal] Add fine-grained pricing strategy for Transition

### ISSUE THREAD

**Issue by randomsleep** [AleoHQ/snarkVM#2334]
## What's the issue?

Currently, if an `Execution` contains no finalization, it will only pay for the storage (1 microcredit per byte):

https://github.com/AleoHQ/snarkVM/blob/21c9ca15cdf68dfcc54651943c61279c6db15258/synthesizer/src/vm/helpers/cost.rs#L61

This may introduce DOS attack in some circumstances.

According to this test: https://github.com/AleoHQ/snarkVM/pull/2333, an empty transition only costs `1153` microcredits. An `Execution` with 64 inputs and 64 outputs only costs `7558` microcredits. Every `input` and `output` will be indexed, so they will create insert operations into the disk and will consume more storage than expected.

## 💥 Proposal

Add fine-grained pricing strategy:

1. Add `transaction_base_cost` for `Transaction`.
2. Add `transition_base_cost` for each `Transition`.
3. Add `input_output_base_cost` for each `Input` and `Output`.

**Comment by vicsn** [comment]
Hi @randomsleep thank you for the suggestions. 

The storage cost for executions is already on the high end, since we might upgrade to light clients where executions won't be stored anymore.
As for the compute, this recent PR adds a fixed execution cost: https://github.com/AleoHQ/snarkVM/pull/2294/files
We considered to parametrize it, but the verification time doesn't vary a lot between Executions.

Closing this one for now but new suggestions are always welcome, really appreciate it.

**Comment by randomsleep** [comment]
Hi @vicsn thanks for the quick response. Just noticed the PR. It looks great.

I think it's not just about the storage size. Every `input` and `output` will be indexed and will create random read and random write access to the disk. Random read and write is slow compared to computation and usually takes most of the execution time (like EVM). Currently an `Execution` can contains `(2 ** 5) * (16 + 16) = 1024` inputs and outputs.

I am curious can the light client avoid the random access pattern introduced by `input` and `output`?

**Comment by d0cd** [comment]
@randomsleep 
The underlying storage is a KV store and has different cost/runtime model than EVM memory. 
I agree that its important to consider the storage **space** and **time**. 
We currently account for storage **space** with microcredits/byte + fixed execution cost. 
The intention is that this would be a proxy for storage **time**.

We'd need some benchmarks to analyze the differences in storage time and verify whether or not this cost is accounted for.
