### ISSUE TITLE
what is BLS12-377 G1/G2 generator used in Aleo， Why Aleo does not use the generator specified in EIP2539?

### ISSUE THREAD

**Issue by readygo67** [AleoHQ/snarkVM#2335]
I try to read the powers-of-beta-15.usrs in github.com/AleoHQ/snarkVM/parameters/src/testnet3, and found the first G1 point is 
```go
X:89363714989903307245735717098563574705733591463163614225748337416674727625843187853442697973404985688481508350822,
Y: 3702177272937190650578065972808860481433820514072818216637796320125658674906330993856598323293086021583822603349,
```
according my understanding, the first G1 point is G1 generator.

in https://eips.ethereum.org/EIPS/eip-2539，the G1 generator is represented in hex as follow:
```go
G1:
X = 0x008848defe740a67c8fc6225bf87ff5485951e2caa9d41bb188282c8bd37cb5cd5481512ffcd394eeab9b16eb21be9ef
Y = 0x01914a69c5102eff1f674f5d30afeec4bd7fb348ca3e52d96d182ad44fb82305c2fe3d3634a9591afd82de55559c8ea6
```
whose decimal value is below
```go
X: 81937999373150964239938255573465948239988671502647976594219695644855304257327692006745978603320413799295628339695, 
Y: 241266749859715473739788878240585681733927191168601896383759122102112907357779751001206799952863815012735208165030,
```
the G1 generator in Aleo DOES NOT EQUAL TO that in eip-2539,  so what's the G1 generator in Aleo? 

EIP2539 snip:
![image](https://github.com/AleoHQ/snarkVM/assets/78890754/a78361ac-68fb-4d12-8f6f-a690c1dd5727)

**Comment by howardwu** [comment]
Closing because we are not an L2 nor are we Ethereum.
