### ISSUE TITLE
Extraneous `set_constraint_limit` usage

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkVM#2339]
Extraneous `set_constraint_limit` usage:

When triggering `call`, no logic above this resets the constraint limit AFAIK.

_Originally posted by @howardwu in https://github.com/AleoHQ/snarkVM/pull/2271#discussion_r1483795188_

**Comment by howardwu** [comment]
The point I'm getting at is the `call.rs` case of `CheckDeployment` never changes the child constraint limit.

**Comment by vicsn** [comment]
I see now, you are right. Because we recently changed `CheckDeployment` so it never actually *executes* the child circuit - because any child function is from a previously deployed program. So [this PR was useless](https://github.com/AleoHQ/snarkVM/pull/2340). Removing the check...

**Comment by howardwu** [comment]
Awesome, glad we're in agreement. Thanks @vicsn
