### ISSUE TITLE
[Bug] Aleo variable index array access

### ISSUE THREAD

**Issue by Thormeard** [AleoHQ/snarkVM#2409]
## 🐛 Bug Report

I am executing an array example from the documentation in snarkvm but it does not work for me. I get this error message: `Failed to parse string. Remaining invalid string is: "r0[r1] into r2; output r2;` Am I doing something wrong? I am aware that variable index access it is not possible in leo but the documentation is for aleo and it looks like it should work.

https://developer.aleo.org/aleo/language#array

## Steps to Reproduce

1. Take code from the example:
```
program arraytest.aleo;

function get_array_element:
    input r0 as [boolean; 4u32].public;
    input r1 as u32.public;
    r0[r1] into r2;
    output r2;
```

2. And try to execute it (I am using `snarkvm execute --offline get_array_element "[true,false,true,false]" 2u32`).
![image](https://github.com/AleoHQ/snarkVM/assets/25845025/8203442e-7ab1-4fd7-98fc-4e278286c434)

If I use constant index it works: 
```
program arraytest.aleo;


function get_array_element:
    input r0 as [boolean; 4u32].public;
    input r1 as u32.public;
    output r0[2u32] as boolean.public;
```
![image](https://github.com/AleoHQ/snarkVM/assets/25845025/8d7d78ac-099e-4587-b7a3-3d2d02f1942c)

But with variable it is an error:
```
program arraytest.aleo;


function get_array_element:
    input r0 as [boolean; 4u32].public;
    input r1 as u32.public;
    output r0[r1] as boolean.public;
```
![image](https://github.com/AleoHQ/snarkVM/assets/25845025/af542cbd-87ab-4f17-a060-791430aef912)

## Expected Behavior

Should be possible to access array with a variable index. (or change example in documentation not to confuse people)

## Your Environment

- snarkVM Version: `v0.16.19`
- Rust Version: `rustc 1.77.0 (aedd173a2 2024-03-17)`
- Computer OS: `macOS 14.4`

**Comment by d0cd** [comment]
This is a documentation issue.
Variable index access is not supported in snarkVM.
Tracking issue here: https://github.com/AleoHQ/welcome/issues/351
