### ISSUE TITLE
[Bug] Panic while decrypting a transaction record

### ISSUE THREAD

**Issue by kellpossible** [AleoHQ/snarkVM#243]
## 🐛 Bug Report

I have some code to test decrypting a transaction record. In this example I decided to modify the encrypted record slightly so that it would not successfully decrypt.

```rust
use snarkos_objects::AccountViewKey;
use snarkos_rpc_client::{SnarkOSRpcConn, methods::get_block_count};
use snarkos_dpc::{record_encryption::RecordEncryption, SystemParameters, instantiated::Components, EncryptedRecord};
use snarkos_utilities::bytes::FromBytes;

use std::str::FromStr;

pub fn decrypt_transaction_record() {
    let system_parameters = SystemParameters::load().unwrap();
    let account_view_key = AccountViewKey::<Components>::from_str("AViewKey1m8gvywHKHKfUzZiLiLoHedcdHEjKwo5TWo6efz8gK7wF").unwrap();

    let encrypted_transaction_bytes = hex::decode(
              "081e4a0d39c6e22d8b4a170af02311f4ba76b4ffba99811\
                    0c6ae9854d288bb1b0df491df24446102ccee297d29ad376af\
                    b46718ce9c9535bfa4596f831e8979807aa9a81ee5f25dbf9d\
                    6046ce7012e976f6031419d535ffec255fc3e5e919ee00a8b2\
                    7b4eaa21b83bffdc9cf417dd760352170915a292761ae4b33f\
                    8604dd82601b345fdf4142ffc422387b06e05836ddae59e5bc\
                    b8782e458e79de894be85980b2a984492dc4e5e3928b73e9c3\
                    31ed6fe901f23204ce246c441d00be2f0b2b00573cf8e16d65\
                    664416da025ce9d10179ae6c60a8ac3c94aef6d06adeab8c09\
                    904eaeb83825f15894b84f394ed70e7b9ddb6dfacbeaa30bed\
                    7063dcb9796766e125c00").unwrap();

    let encrypted_record = EncryptedRecord::read(&encrypted_transaction_bytes[..]).unwrap();

    let record = RecordEncryption::decrypt_record(&system_parameters, &account_view_key, &encrypted_record).unwrap();
    println!("record: {:?}", record);
}
```

I get the following panic:

```txt
thread 'snarkos::tests::test_decrypt_record' panicked at 'assertion failed: `(left == right)`
  left: `QuadraticNonResidue`,
 right: `QuadraticResidue`', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-algorithms-1.1.4/src/encoding/elligator2.rs:232:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84b047bf64dfcfa12867781e9c23dfa4f2e6082c/library/std/src/panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/84b047bf64dfcfa12867781e9c23dfa4f2e6082c/library/std/src/panicking.rs:429
   2: snarkos_algorithms::encoding::elligator2::Elligator2<P,G>::decode
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-algorithms-1.1.4/src/encoding/elligator2.rs:232
   3: snarkos_dpc::base_dpc::record::record_serializer::decode_from_group
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-dpc-1.1.4/src/base_dpc/record/record_serializer.rs:50
   4: <snarkos_dpc::base_dpc::record::record_serializer::RecordSerializer<C,P,G> as snarkos_models::dpc::record_serializer::RecordSerializerScheme>::deserialize
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-dpc-1.1.4/src/base_dpc/record/record_serializer.rs:287
   5: snarkos_dpc::base_dpc::record::record_encryption::RecordEncryption<C>::decrypt_record
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-dpc-1.1.4/src/base_dpc/record/record_encryption.rs:156
   6: voyager::snarkos::decrypt_transaction_record
```

## Expected Behavior

I wouldn't expect the code to panic like this, I think it should return an error that can be handled.

## Your Environment

snarkOS libraries `1.1.4`
Rust `1.47.0-beta.2`
Linux

**Comment by ljedrz** [comment]
Transferred from snarkOS.

The assertion that panics is still in place.

**Comment by ljedrz** [comment]
There are a few assertions and debug assertions in `Elligator2::decode`; in general, user-input-facing code shouldn't panic.

This particular panic could be avoided by e.g. changing
```
assert_eq!((-(u * &x) * &(x + &a)).legendre(), LegendreSymbol::QuadraticResidue);
```
to
```
if (-(u * &x) * &(x + &a)).legendre() != LegendreSymbol::QuadraticResidue {
    return Err(EncodingError::InvalidEncoding); // a new, broad variant
}
```

**Comment by weikengchen** [comment]
I am recently working on field encryption, which likely may replace the group encryption here.

I personally have concerns for elligator 2, since inverse elligator is not guaranteed to be a one-one mapping, and handling curves with a cofactor is also tricky.

**Comment by weikengchen** [comment]
(and for me to understand this issue better, does it occur for manipulated records only, or also normally generated records?)

**Comment by ljedrz** [comment]
According to the original description, this particular record was modified by hand.

**Comment by weikengchen** [comment]
I agree with the change you propose:
```
if (-(u * &x) * &(x + &a)).legendre() != LegendreSymbol::QuadraticResidue {
    return Err(EncodingError::InvalidEncoding); // a new, broad variant
}
```

Do you want to make a PR over it? I think this is needed for the group encryption.

**Comment by ljedrz** [comment]
I'll be happy to - there are other `assert`s in that method, though, so please let me know if there are any other potential panics that should be transformed into normal errors or `debug_assert`s which will only panic in test conditions.

**Comment by weikengchen** [comment]
I look at the code --- there seems to be more potential panics than I think.

Besides `assert`, 
- https://github.com/AleoHQ/snarkVM/blob/master/algorithms/src/encoding/elligator2.rs#L185 may fail if `y = 1`
- https://github.com/AleoHQ/snarkVM/blob/master/algorithms/src/encoding/elligator2.rs#L186 may fail if `y = 1` or `x = 0`
- https://github.com/AleoHQ/snarkVM/blob/master/algorithms/src/encoding/elligator2.rs#L247 may fail if `x = 0`

Let me look at the code more carefully and probably add a few tests for the corner cases to make sure these cases are all captured.

**Comment by kellpossible** [comment]
> According to the original description, this particular record was modified by hand.

Originally yes, but I was also getting this with normally generated records https://github.com/AleoHQ/snarkVM/issues/243#issuecomment-699509687
