### ISSUE TITLE
When you are going build with rust on Linux 

### ISSUE THREAD

**Issue by jamesatomc** [AleoHQ/snarkVM#2488]
You must install this first.

sudo apt-get install curl git-all cmake gcc libssl-dev pkg-config libclang-dev libpq-dev build-essential

User version wants to run node

**Comment by vicsn** [comment]
Thank you for the suggestions. One will want to run the snarkOS binary as node, that repo has build instructions noted in the README for ubuntu - PR is open for debian https://github.com/AleoNet/snarkOS/pull/3041

**Comment by damons** [comment]
Are you saying you want to have a `.deb` package for snarkOS?  Not sure what this issue is describing/asking for.

**Comment by jamesatomc** [comment]
Compiler time with Rust. People who use Rust generally don't need to install much, but when building a Blockchain project aleo or sui, aptos, rooch,...  You must install it because it is very necessary. If you don't install it as mentioned above, you may not be able to build the program. An error like cc will occur.


But people who use Windows Compiler will rarely have a problem. Because you can edit the installation with visual studio and install the C++ package, you can use it. 

@damons

**Comment by jamesatomc** [comment]
Compiler time with Rust. People who use Rust generally don't need to install much, but when building a Blockchain project aleo or sui, aptos, rooch,... Must be installed because it is very necessary. If not installed as mentioned, it may not work.

**Comment by zosorock** [comment]
@jamesatomc are you suggesting we should have a [build_ubuntu.sh](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/build_ubuntu.sh#L10-L21) script like the one we have in snarkOS, telling people the required libraries to build?

**Comment by jamesatomc** [comment]
I saw it last week. At first I thought it wasn't there.
