### ISSUE TITLE
[Bug] Incorrect `next_coinbase_target` update

### ISSUE THREAD

**Issue by randomsleep** [AleoHQ/snarkVM#2505]
[This PR](https://github.com/AleoNet/snarkVM/pull/2410) introduces incorrect `next_coinbase_target` update.  It will retarget once the `cumulative_proof_target` reaches 1/2 of `coinbase_threshold`. However,  the `next_coinbase_target ` is using wrong `last_coinbase_target()`: during time [previous_block.last_coinbase_timestamp(), next_timestamp] the `cumulative_proof_target` is 1/2 of `last_coinbase_target` instead of the whole of `last_coinbase_target`. This makes `next_coinbase_target` higher than expected.

```
        let next_coinbase_target = coinbase_target(
            previous_block.last_coinbase_target(),
            previous_block.last_coinbase_timestamp(),
            next_timestamp,
            N::ANCHOR_TIME,
            N::NUM_BLOCKS_PER_EPOCH,
            N::GENESIS_COINBASE_TARGET,
        )?;
```

In this case, the target will never reach a steady state even if the proving power is constant. Proof: Suppose the proving power is constant (`c` proofs per  `anchor_time`) and we are in a steady state. This means that the steady `coinbase_target` is `2c` (can finish 1/2 of `coinbase_target` in `anchor_time`). However, due to an incorrect `next_coinbase_target` update, the next coinbase_target will be incorrectly higher (the code logic thinks that the network has finished all of the `coinbase_target` in `anchor_time`). This means that such a steady state won't hold.

## Impact

The above shows that an incorrect `coinbase_target` update will drastically fluctuate in `coinbase_target` and `proof_target`. This means a prover can gain huge advantages if it withholds some solution and releases that in proper time. This will eventually lead to an unstable network and unpredictable coinbase reward.

**Comment by d0cd** [comment]
It is true that in steady state the coinbase target would be `2t`, where `t` is the steady state coinbase target if retargeting was performed when the `cumulative_proof_target >= coinbase_target`.
However, this algorithm still reaches, an albeit higher, steady state. 


The proof above proof assumes that the target is in steady state. 
This implies that 1/2 the coinbase target is achieved every `anchor_time` seconds, which would not result in a change to the target.

**Comment by d0cd** [comment]
Closing this issue for now, but please feel free to reopen if you have any strong concerns.
