### ISSUE TITLE
[Bug] Deprecated endpoints in snarkOS still in snarkVM code

### ISSUE THREAD

**Issue by andrezorzo** [AleoHQ/snarkVM#2566]
## 🐛 Bug Report

Few endpoints were deprecated in snarkOS by the following PR https://github.com/AleoNet/snarkOS/pull/3347 

snarkVM code still referencing them:
https://github.com/AleoNet/snarkVM/blob/dea322b3d374ac0fa7dae26cf006bf67acd52e9e/ledger/query/src/query.rs#L64-L102

**Comment by zosorock** [comment]
Resolved by #2567
