### ISSUE TITLE
[Feature] Remove `is_dummy` from `Record` struct and add implicit inner circuit enforcement

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkVM#306]
## 🚀 Feature

Remove `is_dummy` from `Record` struct and add implicit inner circuit enforcement. We can also forgo encoding and encrypting it into encrypted records - note that this doesn't change the encrypted record size, however it should ever so slightly decrease the constraint count of the inner circuit. However, the added enforcement of `is_dummy` is accrued in the inner circuit (but we should be doing this check).

## Motivation

(Outline your motivation here)

## Implementation

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by raychu86** [comment]
Relevant issue - https://github.com/AleoHQ/snarkOS/issues/343.

**Comment by howardwu** [comment]
Also, we should rename this check to `is_noop`.

**Comment by howardwu** [comment]
This change will improve the `record_commitment` constraint cost and native size cost. We currently allocate the bit as a byte and pay for 1 extra byte wherever this `record_commitment` is checked.

**Comment by Pratyush** [comment]
This enables differentiating between normal transactions and transactions that use dummy records, no?

**Comment by howardwu** [comment]
Closing as dummy records will no longer be necessary with design changes.
