### ISSUE TITLE
[Proposal] `BlockHeader` upgrades

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkVM#363]
## 💥 Proposal

This proposal documents an iterative process towards upgrading the architecture of the `BlockHeader` struct in `testnet2` in order to support light-clients and new features as part of general upgrades to Aleo.

The existing block header design is as follows:
```rs
pub struct BlockHeader {
    /// Hash of the previous block - 32 bytes
    pub previous_block_hash: BlockHeaderHash,
    /// Merkle root representing the transactions in the block - 32 bytes
    pub merkle_root_hash: MerkleRootHash,
    /// Merkle root of the transactions in the block using a Pedersen hash - 32 bytes
    pub pedersen_merkle_root_hash: PedersenMerkleRootHash,
    /// Proof of Succinct Work
    pub proof: ProofOfSuccinctWork,
    /// The block timestamp is a Unix epoch time (UTC) when the miner
    /// started hashing the header (according to the miner). - 8 bytes
    pub time: i64,
    /// Proof of work algorithm difficulty target for this block - 8 bytes
    pub difficulty_target: u64,
    /// Nonce for solving the PoW puzzle - 4 bytes
    pub nonce: u32,
}
```

This design includes a few notable shortcomings. For one, we currently do not checkpoint the root of the ledger commitments and serial numbers as part of the block header hash. In addition, the current design requires duplicate computation of the root of the transactions as `merkle_root_hash` and `pedersen_merkle_root_hash`. Third, the design can be improved to simplify common look up operations in light-clients, and for inclusion proofs of specific transactions, commitments, serial numbers, etc. in a SNARK.

The following is a proposal for a new design of the `BlockHeader` struct:
```rs
pub struct BlockHeader {
    /// The previous block header hash - 32 bytes
    pub previous_block_hash: BlockHeaderHash,
    /// The Merkle root representing the transactions in the block - 32 bytes
    pub transactions_root: PedersenMerkleRootHash,
    /// The Merkle root representing the ledger commitments - 32 bytes
    pub commitments_root: MerkleRootHash,
    /// The Merkle root representing the ledger serial numbers - 32 bytes
    pub serial_numbers_root: MerkleRootHash,
    /// The Merkle root representing the ledger program registry - 32 bytes
    pub program_registry_root: MerkleRootHash,
    /// The Merkle root representing the ledger datastore - 32 bytes
    pub datastore_root: MerkleRootHash,
    /// The block header metadata - 20 bytes
    pub metadata: BlockHeaderMetadata,
    /// Proof of Succinct Work
    pub proof: ProofOfSuccinctWork,
}

pub struct BlockHeaderMetadata {
    /// The block timestamp as Unix epoch time (UTC) when the miner
    /// started hashing the header (according to the miner). - 8 bytes
    pub timestamp: i64,
    /// Difficulty target for the PoW puzzle - 8 bytes
    pub difficulty_target: u64,
    /// Nonce for solving the PoW puzzle - 4 bytes
    pub nonce: u32
}
```
Notably, this new design structures the `BlockHeader` fields as leaves in a Merkle tree, in order to make proofs about inclusion of specific individual transactions, commitments, serial numbers, etc. simple to demonstrate to other parties. In addition, the new block header design will switch existing hashing from `SHA256` to `BHP` in order to make the design SNARK-friendly.

In the new design, the current `BlockHeader::merkle_root_hash` would be renamed to `BlockHeader::transactions_root`.

## Genesis Block Header

A genesis block header enforces as convention the following requirements:
- `previous_block_hash` is `0x0000...0000` (32 bytes)
- `transactions_root` is the Merkle root of the genesis block transactions (32 bytes)
- `commitments_root` is the Merkle root of the genesis commitments (32 bytes)
- `serial_numbers_root` is the Merkle root of the genesis serial numbers (32 bytes)
- `program_registry_root` is the Merkle root of the genesis program registry (32 bytes)
- `datastore_root` is the Merkle root of the genesis datastore (32 bytes)
- `metadata.timestamp` is `0i64` (8 bytes)
- `metadata.difficulty_target` is `0xFFFF...FFFF` (8 bytes)
- `metadata.nonce` is a valid nonce for the following `proof` (4 bytes)
- `proof` is a valid zero-knowledge proof of the above variables

## Considerations / Open Questions

- Would it be useful to include the `inner_circuit_ids`, `outer_circuit_ids`, and `universal_srs_ids`?
- Should `metadata.timestamp` be represented as a `u64`? I'm considering the case for possibly proving current consensus checks (e.g. timestamp is within a 2 hour range) in a circuit, or for use in Leo applications downstream in a minimally error-prone/unambiguous representation.

**Comment by Protryon** [comment]
```
    /// The Merkle root representing the transactions in the block - 32 bytes
    pub transactions_root: MerkleRootHash,
```
What are "transactions in the block" the memos of transactions? Transaction IDs? A hash of each transaction blob in a merkle tree? Isn't `BlockHeader::merkle_root_hash` the merkle root hash of commitments?

What's the rationale behind outlining `BlockHeaderMetadata`?

Do the SNARKs need to reason about the program registry or data store root? If not, we should consider a more performant hashing algorithm than blake2s.

**Comment by howardwu** [comment]
```
What are "transactions in the block" the memos of transactions? Transaction IDs? A hash of each transaction blob in a merkle tree? Isn't BlockHeader::merkle_root_hash the merkle root hash of commitments?
```
In the new design, the current `BlockHeader::merkle_root_hash` would be renamed to `BlockHeader::transactions_root`.

```
What's the rationale behind outlining BlockHeaderMetadata?
```
The main rationale, was just to emphasize that this is 1 leaf in the new block Merkle tree.

```
Do the SNARKs need to reason about the program registry or data store root? If not, we should consider a more performant hashing algorithm than blake2s.
```
The will need to prove inclusion from the records when being spent.
