### ISSUE TITLE
Optimize masked Pedersen hashes in POSW

### ISSUE THREAD

**Issue by kobigurk** [AleoHQ/snarkVM#401]
To achieve better amortization resistance, we should optimize the masked Pedersen hash.

Currently we use two-bit lookups for both coordinates of each generator and normal Edwards addition.

Main idea for optimization - use the Montgomery form of the Edwards curve, which would require us to use powers of the same generator for as long as we can (~50-70 powers). The main point we must take care of is that the identity point can't be added when using this form.

**Comment by ljedrz** [comment]
Transferred the issue to snarkVM, as `posw` no longer resides in snarkOS.
