### ISSUE TITLE
Difficulty is subject to manipulation by adjusting the timestamp when mining a new block. 

### ISSUE THREAD

**Issue by apruden2008** [AleoHQ/snarkVM#539]
https://github.com/AleoHQ/snarkVM/blob/4bac7414bd117964df989fdfda3c52a68380c976/dpc/src/ledger/blocks.rs#L409

Proof-of-Succinct work currently uses Bitcoin's difficulty re-targeting algorithm, with the main difference being that `NUM_BLOCKS_PER_RETARGET` referenced above is set to one. This means difficulty is re-targeted dynamically every block, as opposed to over some epoch. For example, Bitcoin re-targets difficulty every 2016 blocks (or roughly two weeks in real-world time). 

A challenge that arises from re-targeting difficulty every block is that it makes the difficulty much easier to manipulate. This is because difficulty is calculated based on the *difference* of the `previous_timestamp` and the `timestamp`. If you can unilaterally control the value of the timestamp (which is possible since each miner that produces a block chooses that value), you can effectively drive difficulty up or down arbitrarily, depending on whatever is most advantageous. 

The result is that dynamic retargeting using the 'bitcoin_retarget' algorithm generally makes selfish mining much easier. Moreover, even when all miners are honest, variations in the individual system clocks will inherently result in unpredictability for miner performance. 

One possible solution is to remove/reduce the control miners have over the timestamp included in the difficulty retargeting algorithm by having some kind of "global" clock for the network. Another solution is Bitcoin's which averages the timestamps over a longer period making it more difficult to manipulate.

**Comment by apruden2008** [comment]
More proposed solutions: 

- A SMA (simple moving average) will allow us to prevent timestamp manipulation, and help mitigate selfish mining using stockpiled block
- Maximum future block time will likely have little relevance. It simply dictates how the leading miner will broadcast their stockpiled blocks (all at once or once every valid MAXIMUM_FUTURE_BLOCK_TIME)
- Mining pools likely won’t solve the issues of a miners with a majority hashrate from winning because it won’t take into account the stockpiling, timestamp tricks, etc. (Though it will allow us to assign some scores to smaller miners for incentivized testnet)
- SMA’s have an additional consideration of hash rate spikes. (Wait 4096 blocks till the avg hash rate has gone down, then blast my machine/pool for the next 4096 blocks while the difficulty is low, then wait another cycle) Selecting this range is also fairly important: https://github.com/zawy12/difficulty-algorithms/issues/14
- An EMA (exponential moving average) might be better to smooth out the effective hash rate of the network. https://read.cash/@jtoomim/bch-upgrade-proposal-use-asert-as-the-new-daa-1d875696 (edited) 
- Overall, the main issue is the fact that singular parties have access to techniques that give them a majority of hashrate. No matter what mitigating factors we add, they’ll be able to blast ahead and win blocks. The best thing to do is to internally develop/use techniques like GPU mining

ASERT algorithm:
exponent = (time_delta - ideal_block_time * (height_delta + 1)) / halflife
next_target = anchor_target * 2**(exponent)
"The form (2) displays a remarkable property, which is that when you push the schedule ahead by an additional time +τ , the difficulty must increase by a factor ×e, without exception. Sustained rapid mining would require getting more and more ahead of schedule, producing an exponentially rising difficulty, and thus after a short time (some multiple of τ ) the rapid mining would become impractically hard."
 BCH uses this technique because they use a 144 block window = 1 day. Which is much more prone to attack than bitcoin’s 2 week adjustment (which is stable only because the hash rate is so distributed).

**Comment by marco-storswift** [comment]
I don't think it's a good idea to use the system chrono::Utc::now().timestamp() to identify a timestamp in the blockchain. As long as the system time is used, it becomes an uncertain factor.
It is recommended to use information from the previous block with some offset, but then there should be null blocks. The core logic is that when everyone calculates the next block, the basic parameters should be the same, and the comparison should only be the size of the calculation force. The current situation is that the base information of each computed block is different
It is not a reasonable argument to use the mine_next_block entry time as the cumulative_weight of the block. The core factor of cumulative_weight should be block_height or the number of wrapped transactions

**Comment by xorinox** [comment]
re:  Overall, the main issue is the fact that singular parties have access to techniques that give them a majority of hash-rate. No matter what mitigating factors we add, they’ll be able to blast ahead and win blocks. The best thing to do is to internally develop/use techniques like GPU mining

If thousands of severs & miners, wouldn't produce, if they eventually do, proofs and blocks, that anyways aren't going to win, mostly due to timestamp issue described, the situation might look a bit different.  There is no proof, what the situation would look like, if these thousands of servers, would aim to produce blocks, that can actually win.

**Comment by iamnader** [comment]
Here is the conversation the Bitcoin devs had about this issue a decade ago. Still relevant. 

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2011-September/thread.html#514

**Comment by apruden2008** [comment]
> Here is the conversation the Bitcoin devs had about this issue a decade ago. Still relevant.
> 
> https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2011-September/thread.html#514

That's a fantastic bit of history. thanks for digging that up and sharing.
