### ISSUE TITLE
[Bug] CLI update command

### ISSUE THREAD

**Issue by murka** [AleoHQ/snarkVM#559]
## 🐛 CLI update command
SnarkVM cannot find the latest tag in the repository

![screenshot](https://screenshots.niina.xyz/2022-01-01_23-08-19-265.png)

## Your Environment

snarkVM: v0.7.9
Rust: v1.57.0
OS: Ubuntu 21.10 x86_64

**Comment by yujqiao** [comment]
https://github.com/AleoHQ/snarkVM/releases Because no releases were made. There are only tags. :(

**Comment by murka** [comment]
So, I think, when the bug (the first release) is fixed, we can close this issue.

**Comment by howardwu** [comment]
Closing as the command is behaving correctly.
