### ISSUE TITLE
[Bug] Can't Build the snarkVM MSM CUDA Program

### ISSUE THREAD

**Issue by africancu** [AleoHQ/snarkVM#569]
MyEnvironment

**OS version:** Ubuntu20.04
**cuda version:** 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

GPU Driver is OK。

root@worker07:\~# cd snarkVM/algorithms/src/msm/variable_base/blst_377_cuda

root@worker07:\~/snarkVM/algorithms/src/msm/variable_base/blst_377_cuda# ./build.sh
./asm_cuda.cu(599): warning #549-D: variable "r" is used before its value is set

./asm_cuda.cu(702): warning #549-D: variable "r" is used before its value is set

./blst_377_ops.cu(63): warning #174-D: expression has no effect

./blst_377_ops.cu(439): warning #1622-D: null argument provided for parameter marked with attribute "nonnull"

./blst_377_ops.cu(450): error: **argument of type "const blst_p1_affine *" is incompatible with parameter of type "const blst_p1 *"**

1 error detected in the compilation of "./blst_377_ops.cu".
./msm.cu(6): warning #177-D: variable "BLST_WIDTH" was declared but never referenced

./asm_cuda.cu(599): warning #549-D: variable "r" is used before its value is set

./asm_cuda.cu(702): warning #549-D: variable "r" is used before its value is set

./blst_377_ops.cu(63): warning #174-D: expression has no effect

./blst_377_ops.cu(439): warning #1622-D: null argument provided for parameter marked with attribute "nonnull"

./blst_377_ops.cu(450): error: argument of type "const blst_p1_affine *" is incompatible with parameter of type "const blst_p1 *"

1 error detected in the compilation of "./blst_377_ops.cu".
./msm.cu(6): warning #177-D: variable "BLST_WIDTH" was declared but never referenced

What is the reason for this ?

**Comment by onsraorg** [comment]
Hello, have you solved this problem? I also met temporarily

**Comment by raychu86** [comment]
This issue should be resolved with the new design
