### ISSUE TITLE
[Bug] cargo bench for GPU fails with error SIGSEGV: invalid memory reference

### ISSUE THREAD

**Issue by davaymne** [AleoHQ/snarkVM#578]
GPU: NVIDIA GeForce RTX 3090
CUDA: NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5
SnarkVM: rev 2af7756

When I try to run 
`cargo bench --bench posw --features "snarkvm-algorithms/cuda"`
I geterror:
```
error: process didn't exit successfully: `/root/snarkVM/target/release/deps/posw-da01fa784668507f --bench` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by raychu86** [comment]
Try running the `build.sh` file in `algorithms/src/msm/variable/base/blst_377_cuda` and locally adjust the commands as needed to support your version of CUDA. There is a quick build guide in the same directory that may be useful as well. 

We are likely going to deprecate this version of our CUDA impl soon, so if this doesn't work, keep an eye out for when we merge the updated version.

**Comment by davaymne** [comment]
When I do `build.sh` - I get exact the same issue as per https://github.com/AleoHQ/snarkVM/issues/569

**Comment by xorinox** [comment]
Had the same issue when using more recent CUDA version and NV driver.. Using older version things work

GPU: NVIDIA GeForce RTX 3080
Driver:  470.86, Cuda: 11.3.1-4
SnarkVM: rev 2af7756
OS:  Pop!_OS 21.10
Kernel:    5.15.11-76051511-generic


on 12900k, finishes one proof in about ~1000 ms

`Block height 156079: 4 proof(s) created 1010 ms on average, 59.4 H/min...`
`Block height 156079: 8 proof(s) created 1001 ms on average, 59.9 H/min...`
`Block height 156079: 12 proof(s) created 1002 ms on average, 59.9 H/min...`
`Block height 156079: 16 proof(s) created 1002 ms on average, 59.8 H/min...`
`Block height 156079: 20 proof(s) created 1003 ms on average, 59.8 H/min...`
`Jan 12 00:10:03 node-11: block height 156079, 20 hashes @ 21.241261 seconds -> 56.500000 H/min`

**Comment by raychu86** [comment]
Should be resolved with new GPU model.
