### ISSUE TITLE
[Bug] Can't compile snarkvm-curves crate in vendored mode

### ISSUE THREAD

**Issue by happysalada** [AleoHQ/snarkVM#587]
## 🐛 Bug Report

Hi, thanks a lot for the software first of all!

In the snarkVM-curves crate, the source code doesn't include documentation (ref  https://docs.rs/crate/snarkvm-curves/0.7.9/source/src/lib.rs) even though there is an include macro for documentation. This doesn't matter for most used case, but trying to use the crate in vendored mode will fail.

Would you mind incuding the documentation in the source of the crate ?

I'm coming here from trying to add snarkOS to nixos, so ideally if you can release a newer version of this crate after that and update the snarkOS dependency that would be amazing. Of course if you need help, let me know.

(Write your description here)

## Steps to Reproduce

issue is with downstream usage of this crate.

```
error: couldn't read /private/tmp/nix-build-snarkos-unstable-2021-01-12.drv-0/snarkos-unstable-2021-01-12-
vendor.tar.gz/snarkvm-curves/src/../documentation/the_aleo_curves/00_overview.md: No such file or director
y (os error 2)
  --> /private/tmp/nix-build-snarkos-unstable-2021-01-12.drv-0/snarkos-unstable-2021-01-12-vendor.tar.gz/s
narkvm-curves/src/lib.rs:22:10
   |
22 | #![doc = include_str!("../documentation/the_aleo_curves/00_overview.md")]
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrac
e for more info)

error: could not compile `snarkvm-curves` due to previous error
```

## Expected Behavior

snarkVM can be used in vendored mode

## Your Environment

- snarkvm-curves v0.7.5 (https://github.com/AleoHQ/snarkVM.git?rev=2af7756#2af7756c)
- rust version 1.57
- macos

**Comment by happysalada** [comment]
Thank you for taking care of this so fast!
Any chance you could update the snarkVM dependency in snarkOS ?

**Comment by happysalada** [comment]
I just tried updating snarkos and it looks like I can't just randomly take the latest master from snarkvm. I'll wait then.
Thanks again for merging this change so quickly!

**Comment by howardwu** [comment]
Will do!
