### ISSUE TITLE
[Sanity Check] Universal SRS serialization form

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkVM#769]
## 🐛 Bug Report

A number of unit tests in `snarkvm-algorithms` and `snarkvm-dpc` slowed down following the integration of the new universal SRS infrastructure.

Can we confirm that the files are stored in **uncompressed** form? (@julesdesmit) If they're in compressed form, we should update them to uncompressed form. 

If the serialization format isn't the cause of the performance regression, we should look into the cause. There might be something happening that we will want to address before shipping this version of snarkVM.

**Comment by jules** [comment]
I believe the files are stored in compressed form currently - I can convert them to uncompressed form and we can run some tests with it
