### ISSUE TITLE
cargo bench --bench posw  failed with assert!(remainder.is_zero()) in the testnet3 barnch

### ISSUE THREAD

**Issue by marco-storswift** [AleoHQ/snarkVM#888]
## 🐛 Bug Report

cargo bench --bench posw  failed with the testnet3 barnch, the git version is 
SHA-1: 111f5faa1a24342a3d454077e901ea01ea1d5181

## Steps to Reproduce

1. git clone https://github.com/AleoHQ/snarkVM.git  ./vm
2. cd .vm/dpc
3. cargo bench --bench posw.

## Expected Behavior

matrix_sumcheck_helper 131070/65536
matrix_sumcheck_helper 131070/65536
thread '<unnamed>' panicked at 'assertion failed: remainder.is_zero()', D:\work\storswiftlabs\snarkvm\algorithms\src\snark\marlin\ahp\prover\roun
d_functions\third.rs:226:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'assertion failed: remainder.is_zero()', D:\work\storswiftlabs\snarkvm\algorithms\src\snark\marlin\ahp\prover\roun
d_functions\third.rs:226:9
thread '<unnamed>' panicked at 'assertion failed: remainder.is_zero()', D:\work\storswiftlabs\snarkvm\algorithms\src\snark\marlin\ahp\prover\roun
d_functions\third.rs:226:9

i add  log in line#225
        println!("matrix_sumcheck_helper {}/{}", h.degree(), non_zero_domain.size());
        let (mut h, remainder) = h.divide_by_vanishing_poly(non_zero_domain).unwrap();
        assert!(remainder.is_zero());

## Your Environment

- 
- 
- 
snarkVM  111f5faa1a
rust version 1.64
OS： window 11

**Comment by Elhorses** [comment]
+1

**Comment by liuzsen** [comment]
same issue

**Comment by howardwu** [comment]
Closing as this feature has been removed from the `testnet3` branch. Feel free to reopen if you encounter this issue elsewhere!
